//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Document.Services.Compare.Control.ComparerProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompareResponseFlags", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/")]
    public enum CompareResponseFlags : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rtf = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Xml = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Both = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompareResult", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/")]
    [System.SerializableAttribute()]
    public partial class CompareResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RedlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.XmlElement SummaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] Redline {
            get {
                return this.RedlineField;
            }
            set {
                if ((object.ReferenceEquals(this.RedlineField, value) != true)) {
                    this.RedlineField = value;
                    this.RaisePropertyChanged("Redline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Xml.XmlElement Summary {
            get {
                return this.SummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryField, value) != true)) {
                    this.SummaryField = value;
                    this.RaisePropertyChanged("Summary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOptions", Namespace="http://workshare.com/compareservices/5.0/comparewebservice/")]
    public enum ResponseOptions : int {

		[EnumMemberAttribute]
        Rtf = 1,
		[EnumMemberAttribute]
        Xml = 2,
		[EnumMemberAttribute]
        RtfWithSummary = 3,
		[EnumMemberAttribute]
		Wdf = 4,
		[EnumMemberAttribute]
        WdfWithSummary = 6,
		[EnumMemberAttribute]
		Doc = 8,
		[EnumMemberAttribute]
		DocWithSummary = 10,
		[EnumMemberAttribute]
		DocX = 16,
		[EnumMemberAttribute]
		DocXWithSummary = 18,
		[EnumMemberAttribute]
		Pdf = 32,
		[EnumMemberAttribute]
		PdfWithSummary = 34
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompareResults", Namespace="http://workshare.com/compareservices/5.0/comparewebservice/")]
    [System.SerializableAttribute()]
    public partial class CompareResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RedlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SummaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Redline {
            get {
                return this.RedlineField;
            }
            set {
                if ((object.ReferenceEquals(this.RedlineField, value) != true)) {
                    this.RedlineField = value;
                    this.RaisePropertyChanged("Redline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary {
            get {
                return this.SummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryField, value) != true)) {
                    this.SummaryField = value;
                    this.RaisePropertyChanged("Summary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecuteParams", Namespace="http://workshare.com/compareservices/5.0/comparewebservice/")]
    [System.SerializableAttribute()]
    public partial class ExecuteParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompareOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] OriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Document.Services.Compare.Control.ComparerProxy.ResponseOptions ResponseOptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompareOptions {
            get {
                return this.CompareOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.CompareOptionsField, value) != true)) {
                    this.CompareOptionsField = value;
                    this.RaisePropertyChanged("CompareOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Modified {
            get {
                return this.ModifiedField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedField, value) != true)) {
                    this.ModifiedField = value;
                    this.RaisePropertyChanged("Modified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Original {
            get {
                return this.OriginalField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalField, value) != true)) {
                    this.OriginalField = value;
                    this.RaisePropertyChanged("Original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Document.Services.Compare.Control.ComparerProxy.ResponseOptions ResponseOption {
            get {
                return this.ResponseOptionField;
            }
            set {
                if ((this.ResponseOptionField.Equals(value) != true)) {
                    this.ResponseOptionField = value;
                    this.RaisePropertyChanged("ResponseOption");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerformanceResults", Namespace="http://workshare.com/compareservices/5.2/comparewebservice/")]
    [System.SerializableAttribute()]
    public partial class PerformanceResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan ComparisonTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan ModifiedConversionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan ModifiedPreProcessingTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan OriginalConversionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan OriginalPreProcessingTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan ResultsProcessingTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan TotalExecutionTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan ComparisonTime {
            get {
                return this.ComparisonTimeField;
            }
            set {
                if ((this.ComparisonTimeField.Equals(value) != true)) {
                    this.ComparisonTimeField = value;
                    this.RaisePropertyChanged("ComparisonTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan ModifiedConversionTime {
            get {
                return this.ModifiedConversionTimeField;
            }
            set {
                if ((this.ModifiedConversionTimeField.Equals(value) != true)) {
                    this.ModifiedConversionTimeField = value;
                    this.RaisePropertyChanged("ModifiedConversionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan ModifiedPreProcessingTime {
            get {
                return this.ModifiedPreProcessingTimeField;
            }
            set {
                if ((this.ModifiedPreProcessingTimeField.Equals(value) != true)) {
                    this.ModifiedPreProcessingTimeField = value;
                    this.RaisePropertyChanged("ModifiedPreProcessingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan OriginalConversionTime {
            get {
                return this.OriginalConversionTimeField;
            }
            set {
                if ((this.OriginalConversionTimeField.Equals(value) != true)) {
                    this.OriginalConversionTimeField = value;
                    this.RaisePropertyChanged("OriginalConversionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan OriginalPreProcessingTime {
            get {
                return this.OriginalPreProcessingTimeField;
            }
            set {
                if ((this.OriginalPreProcessingTimeField.Equals(value) != true)) {
                    this.OriginalPreProcessingTimeField = value;
                    this.RaisePropertyChanged("OriginalPreProcessingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan ResultsProcessingTime {
            get {
                return this.ResultsProcessingTimeField;
            }
            set {
                if ((this.ResultsProcessingTimeField.Equals(value) != true)) {
                    this.ResultsProcessingTimeField = value;
                    this.RaisePropertyChanged("ResultsProcessingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan TotalExecutionTime {
            get {
                return this.TotalExecutionTimeField;
            }
            set {
                if ((this.TotalExecutionTimeField.Equals(value) != true)) {
                    this.TotalExecutionTimeField = value;
                    this.RaisePropertyChanged("TotalExecutionTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", ConfigurationName="ComparerProxy.IComparer")]
    public interface IComparer {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://workshare.com/compareservices/5.0/comparewebservice/Authenticate", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/AuthenticateResponse")]
        bool Authenticate(string sRealm, string sUser, string sPassword);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://workshare.com/compareservices/5.0/comparewebservice/GetVersion", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/GetVersionResponse")]
        string GetVersion();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://workshare.com/compareservices/5.0/comparewebservice/GetCompositorVersion", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/GetCompositorVersionRe" +
            "sponse")]
        string GetCompositorVersion();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://workshare.com/compareservices/5.0/comparewebservice/GetOptionsSet", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/GetOptionsSetResponse")]
        string GetOptionsSet();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://workshare.com/compareservices/5.0/comparewebservice/SetOptionsSet", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/SetOptionsSetResponse")]
        bool SetOptionsSet(string sOptionsSet);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://workshare.com/compareservices/5.0/comparewebservice/Execute", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/ExecuteResponse")]
        Document.Services.Compare.Control.ComparerProxy.CompareResults Execute(byte[] OriginalData, byte[] ModifiedData, Document.Services.Compare.Control.ComparerProxy.ResponseOptions ResponseOption, string CompareOptions);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://workshare.com/compareservices/5.0/comparewebservice/ExecuteEx", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/ExecuteExResponse")]
        Document.Services.Compare.Control.ComparerProxy.CompareResults ExecuteEx(Document.Services.Compare.Control.ComparerProxy.ExecuteParams execParams);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IComparerChannel : Document.Services.Compare.Control.ComparerProxy.IComparer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ComparerClient : System.ServiceModel.ClientBase<Document.Services.Compare.Control.ComparerProxy.IComparer>, Document.Services.Compare.Control.ComparerProxy.IComparer {
        
        public ComparerClient() {
        }
        
        public ComparerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComparerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComparerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComparerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Authenticate(string sRealm, string sUser, string sPassword) {
            return base.Channel.Authenticate(sRealm, sUser, sPassword);
        }
        
        public string GetVersion() {
            return base.Channel.GetVersion();
        }
        
        public string GetCompositorVersion() {
            return base.Channel.GetCompositorVersion();
        }
        
        public string GetOptionsSet() {
            return base.Channel.GetOptionsSet();
        }
        
        public bool SetOptionsSet(string sOptionsSet) {
            return base.Channel.SetOptionsSet(sOptionsSet);
        }
        
        public Document.Services.Compare.Control.ComparerProxy.CompareResults Execute(byte[] OriginalData, byte[] ModifiedData, Document.Services.Compare.Control.ComparerProxy.ResponseOptions ResponseOption, string CompareOptions) {
            return base.Channel.Execute(OriginalData, ModifiedData, ResponseOption, CompareOptions);
        }
        
        public Document.Services.Compare.Control.ComparerProxy.CompareResults ExecuteEx(Document.Services.Compare.Control.ComparerProxy.ExecuteParams execParams) {
            return base.Channel.ExecuteEx(execParams);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://workshare.com/compareservices/5.2/comparewebservice/", ConfigurationName="ComparerProxy.IComparerChunked")]
    public interface IComparerChunked {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://workshare.com/compareservices/5.0/comparewebservice/) of message AuthenticateRequest does not match the default value (http://workshare.com/compareservices/5.2/comparewebservice/)
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://workshare.com/compareservices/5.0/comparewebservice/Authenticate", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/AuthenticateResponse")]
        Document.Services.Compare.Control.ComparerProxy.AuthenticateResponse Authenticate(Document.Services.Compare.Control.ComparerProxy.AuthenticateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://workshare.com/compareservices/5.0/comparewebservice/) of message GetVersionRequest does not match the default value (http://workshare.com/compareservices/5.2/comparewebservice/)
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://workshare.com/compareservices/5.0/comparewebservice/GetVersion", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/GetVersionResponse")]
        Document.Services.Compare.Control.ComparerProxy.GetVersionResponse GetVersion(Document.Services.Compare.Control.ComparerProxy.GetVersionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://workshare.com/compareservices/5.0/comparewebservice/) of message GetCompositorVersionRequest does not match the default value (http://workshare.com/compareservices/5.2/comparewebservice/)
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://workshare.com/compareservices/5.0/comparewebservice/GetCompositorVersion", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/GetCompositorVersionResponse")]
        Document.Services.Compare.Control.ComparerProxy.GetCompositorVersionResponse GetCompositorVersion(Document.Services.Compare.Control.ComparerProxy.GetCompositorVersionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://workshare.com/compareservices/5.0/comparewebservice/) of message GetOptionsSetRequest does not match the default value (http://workshare.com/compareservices/5.2/comparewebservice/)
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://workshare.com/compareservices/5.0/comparewebservice/GetOptionsSet", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/GetOptionsSetResponse")]
        Document.Services.Compare.Control.ComparerProxy.GetOptionsSetResponse GetOptionsSet(Document.Services.Compare.Control.ComparerProxy.GetOptionsSetRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://workshare.com/compareservices/5.0/comparewebservice/) of message SetOptionsSetRequest does not match the default value (http://workshare.com/compareservices/5.2/comparewebservice/)
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://workshare.com/compareservices/5.0/comparewebservice/SetOptionsSet", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/SetOptionsSetResponse")]
        Document.Services.Compare.Control.ComparerProxy.SetOptionsSetResponse SetOptionsSet(Document.Services.Compare.Control.ComparerProxy.SetOptionsSetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://workshare.com/compareservices/5.2/comparewebservice/InitialiseFile", ReplyAction="http://workshare.com/compareservices/5.2/comparewebservice/InitialiseFileResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://workshare.com/compareservices/5.2/comparewebservice/IComparerChunked/Initi" +
            "aliseFileStringFault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Guid InitialiseFile(string fileID, long sizeBytes);

        [System.ServiceModel.OperationContractAttribute(ProtectionLevel = System.Net.Security.ProtectionLevel.EncryptAndSign, Action = "http://workshare.com/compareservices/5.2/comparewebservice/ReleaseFile", ReplyAction = "http://workshare.com/compareservices/5.2/comparewebservice/ReleaseFileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://workshare.com/compareservices/5.2/comparewebservice/IComparerChunked/Relea" +
            "seFileStringFault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        void ReleaseFile(System.Guid fileGuid);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://workshare.com/compareservices/5.2/comparewebservice/ReleaseAll")]
        void ReleaseAll();

        [System.ServiceModel.OperationContractAttribute(ProtectionLevel = System.Net.Security.ProtectionLevel.EncryptAndSign, Action = "http://workshare.com/compareservices/5.2/comparewebservice/AppendOriginalFile", ReplyAction = "http://workshare.com/compareservices/5.2/comparewebservice/AppendOriginalFileResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://workshare.com/compareservices/5.2/comparewebservice/IComparerChunked/Appen" +
            "dFileStringFault", ProtectionLevel=System.Net.Security.ProtectionLevel.None, Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        void AppendFile(System.Guid guidFile, byte[] fileChunk, long previousBytesSent);

        [System.ServiceModel.OperationContractAttribute(ProtectionLevel = System.Net.Security.ProtectionLevel.EncryptAndSign, Action = "http://workshare.com/compareservices/5.2/comparewebservice/Compare", ReplyAction = "http://workshare.com/compareservices/5.2/comparewebservice/CompareResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://workshare.com/compareservices/5.2/comparewebservice/IComparerChunked/Compa" +
            "reStringFault", ProtectionLevel = System.Net.Security.ProtectionLevel.EncryptAndSign, Name = "string", Namespace = "http://schemas.microsoft.com/2003/10/Serialization/")]
        Document.Services.Compare.Control.ComparerProxy.CompareResults Compare(System.Guid guidOriginalFile, System.Guid guidModifiedFile, Document.Services.Compare.Control.ComparerProxy.ResponseOptions ResponseOption, string CompareOptions);

        [System.ServiceModel.OperationContractAttribute(ProtectionLevel = System.Net.Security.ProtectionLevel.EncryptAndSign, Action = "http://workshare.com/compareservices/5.2/comparewebservice/Benchmark", ReplyAction = "http://workshare.com/compareservices/5.2/comparewebservice/BenchmarkResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://workshare.com/compareservices/5.2/comparewebservice/IComparerChunked/Bench" +
            "markStringFault", ProtectionLevel = System.Net.Security.ProtectionLevel.EncryptAndSign, Name = "string", Namespace = "http://schemas.microsoft.com/2003/10/Serialization/")]
        Document.Services.Compare.Control.ComparerProxy.PerformanceResults Benchmark(System.Guid guidOriginalFile, System.Guid guidModifiedFile, Document.Services.Compare.Control.ComparerProxy.ResponseOptions ResponseOption, string CompareOptions);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Authenticate", WrapperNamespace="http://workshare.com/compareservices/5.0/comparewebservice/", IsWrapped=true)]
    public partial class AuthenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", Order=0)]
        public string sRealm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", Order=1)]
        public string sUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", Order=2)]
        public string sPassword;
        
        public AuthenticateRequest() {
        }
        
        public AuthenticateRequest(string sRealm, string sUser, string sPassword) {
            this.sRealm = sRealm;
            this.sUser = sUser;
            this.sPassword = sPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateResponse", WrapperNamespace="http://workshare.com/compareservices/5.0/comparewebservice/", IsWrapped=true)]
    public partial class AuthenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", Order=0)]
        public bool AuthenticateResult;
        
        public AuthenticateResponse() {
        }
        
        public AuthenticateResponse(bool AuthenticateResult) {
            this.AuthenticateResult = AuthenticateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVersion", WrapperNamespace="http://workshare.com/compareservices/5.0/comparewebservice/", IsWrapped=true)]
    public partial class GetVersionRequest {
        
        public GetVersionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVersionResponse", WrapperNamespace="http://workshare.com/compareservices/5.0/comparewebservice/", IsWrapped=true)]
    public partial class GetVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", Order=0)]
        public string GetVersionResult;
        
        public GetVersionResponse() {
        }
        
        public GetVersionResponse(string GetVersionResult) {
            this.GetVersionResult = GetVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompositorVersion", WrapperNamespace="http://workshare.com/compareservices/5.0/comparewebservice/", IsWrapped=true)]
    public partial class GetCompositorVersionRequest {
        
        public GetCompositorVersionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompositorVersionResponse", WrapperNamespace="http://workshare.com/compareservices/5.0/comparewebservice/", IsWrapped=true)]
    public partial class GetCompositorVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", Order=0)]
        public string GetCompositorVersionResult;
        
        public GetCompositorVersionResponse() {
        }
        
        public GetCompositorVersionResponse(string GetCompositorVersionResult) {
            this.GetCompositorVersionResult = GetCompositorVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOptionsSet", WrapperNamespace="http://workshare.com/compareservices/5.0/comparewebservice/", IsWrapped=true)]
    public partial class GetOptionsSetRequest {
        
        public GetOptionsSetRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOptionsSetResponse", WrapperNamespace="http://workshare.com/compareservices/5.0/comparewebservice/", IsWrapped=true)]
    public partial class GetOptionsSetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", Order=0)]
        public string GetOptionsSetResult;
        
        public GetOptionsSetResponse() {
        }
        
        public GetOptionsSetResponse(string GetOptionsSetResult) {
            this.GetOptionsSetResult = GetOptionsSetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetOptionsSet", WrapperNamespace="http://workshare.com/compareservices/5.0/comparewebservice/", IsWrapped=true)]
    public partial class SetOptionsSetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", Order=0)]
        public string sOptionsSet;
        
        public SetOptionsSetRequest() {
        }
        
        public SetOptionsSetRequest(string sOptionsSet) {
            this.sOptionsSet = sOptionsSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetOptionsSetResponse", WrapperNamespace="http://workshare.com/compareservices/5.0/comparewebservice/", IsWrapped=true)]
    public partial class SetOptionsSetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", Order=0)]
        public bool SetOptionsSetResult;
        
        public SetOptionsSetResponse() {
        }
        
        public SetOptionsSetResponse(bool SetOptionsSetResult) {
            this.SetOptionsSetResult = SetOptionsSetResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IComparerChunkedChannel : Document.Services.Compare.Control.ComparerProxy.IComparerChunked, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ComparerChunkedClient : System.ServiceModel.ClientBase<Document.Services.Compare.Control.ComparerProxy.IComparerChunked>, Document.Services.Compare.Control.ComparerProxy.IComparerChunked {
        
        public ComparerChunkedClient() {
        }
        
        public ComparerChunkedClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComparerChunkedClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComparerChunkedClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComparerChunkedClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Document.Services.Compare.Control.ComparerProxy.AuthenticateResponse Document.Services.Compare.Control.ComparerProxy.IComparerChunked.Authenticate(Document.Services.Compare.Control.ComparerProxy.AuthenticateRequest request) {
            return base.Channel.Authenticate(request);
        }
        
        public bool Authenticate(string sRealm, string sUser, string sPassword) {
            Document.Services.Compare.Control.ComparerProxy.AuthenticateRequest inValue = new Document.Services.Compare.Control.ComparerProxy.AuthenticateRequest();
            inValue.sRealm = sRealm;
            inValue.sUser = sUser;
            inValue.sPassword = sPassword;
            Document.Services.Compare.Control.ComparerProxy.AuthenticateResponse retVal = ((Document.Services.Compare.Control.ComparerProxy.IComparerChunked)(this)).Authenticate(inValue);
            return retVal.AuthenticateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Document.Services.Compare.Control.ComparerProxy.GetVersionResponse Document.Services.Compare.Control.ComparerProxy.IComparerChunked.GetVersion(Document.Services.Compare.Control.ComparerProxy.GetVersionRequest request) {
            return base.Channel.GetVersion(request);
        }
        
        public string GetVersion() {
            Document.Services.Compare.Control.ComparerProxy.GetVersionRequest inValue = new Document.Services.Compare.Control.ComparerProxy.GetVersionRequest();
            Document.Services.Compare.Control.ComparerProxy.GetVersionResponse retVal = ((Document.Services.Compare.Control.ComparerProxy.IComparerChunked)(this)).GetVersion(inValue);
            return retVal.GetVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Document.Services.Compare.Control.ComparerProxy.GetCompositorVersionResponse Document.Services.Compare.Control.ComparerProxy.IComparerChunked.GetCompositorVersion(Document.Services.Compare.Control.ComparerProxy.GetCompositorVersionRequest request) {
            return base.Channel.GetCompositorVersion(request);
        }
        
        public string GetCompositorVersion() {
            Document.Services.Compare.Control.ComparerProxy.GetCompositorVersionRequest inValue = new Document.Services.Compare.Control.ComparerProxy.GetCompositorVersionRequest();
            Document.Services.Compare.Control.ComparerProxy.GetCompositorVersionResponse retVal = ((Document.Services.Compare.Control.ComparerProxy.IComparerChunked)(this)).GetCompositorVersion(inValue);
            return retVal.GetCompositorVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Document.Services.Compare.Control.ComparerProxy.GetOptionsSetResponse Document.Services.Compare.Control.ComparerProxy.IComparerChunked.GetOptionsSet(Document.Services.Compare.Control.ComparerProxy.GetOptionsSetRequest request) {
            return base.Channel.GetOptionsSet(request);
        }
        
        public string GetOptionsSet() {
            Document.Services.Compare.Control.ComparerProxy.GetOptionsSetRequest inValue = new Document.Services.Compare.Control.ComparerProxy.GetOptionsSetRequest();
            Document.Services.Compare.Control.ComparerProxy.GetOptionsSetResponse retVal = ((Document.Services.Compare.Control.ComparerProxy.IComparerChunked)(this)).GetOptionsSet(inValue);
            return retVal.GetOptionsSetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Document.Services.Compare.Control.ComparerProxy.SetOptionsSetResponse Document.Services.Compare.Control.ComparerProxy.IComparerChunked.SetOptionsSet(Document.Services.Compare.Control.ComparerProxy.SetOptionsSetRequest request) {
            return base.Channel.SetOptionsSet(request);
        }
        
        public bool SetOptionsSet(string sOptionsSet) {
            Document.Services.Compare.Control.ComparerProxy.SetOptionsSetRequest inValue = new Document.Services.Compare.Control.ComparerProxy.SetOptionsSetRequest();
            inValue.sOptionsSet = sOptionsSet;
            Document.Services.Compare.Control.ComparerProxy.SetOptionsSetResponse retVal = ((Document.Services.Compare.Control.ComparerProxy.IComparerChunked)(this)).SetOptionsSet(inValue);
            return retVal.SetOptionsSetResult;
        }
        
        public System.Guid InitialiseFile(string fileID, long sizeBytes) {
            return base.Channel.InitialiseFile(fileID, sizeBytes);
        }
        
        public void ReleaseFile(System.Guid fileGuid) {
            base.Channel.ReleaseFile(fileGuid);
        }
        
        public void ReleaseAll() {
            base.Channel.ReleaseAll();
        }
        
        public void AppendFile(System.Guid guidFile, byte[] fileChunk, long previousBytesSent) {
            base.Channel.AppendFile(guidFile, fileChunk, previousBytesSent);
        }
        
        public Document.Services.Compare.Control.ComparerProxy.CompareResults Compare(System.Guid guidOriginalFile, System.Guid guidModifiedFile, Document.Services.Compare.Control.ComparerProxy.ResponseOptions ResponseOption, string CompareOptions) {
            return base.Channel.Compare(guidOriginalFile, guidModifiedFile, ResponseOption, CompareOptions);
        }
        
        public Document.Services.Compare.Control.ComparerProxy.PerformanceResults Benchmark(System.Guid guidOriginalFile, System.Guid guidModifiedFile, Document.Services.Compare.Control.ComparerProxy.ResponseOptions ResponseOption, string CompareOptions) {
            return base.Channel.Benchmark(guidOriginalFile, guidModifiedFile, ResponseOption, CompareOptions);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://workshare.com/compareservices/1.1/comparewebservice/", ConfigurationName="ComparerProxy.ILegacyComparer")]
    public interface ILegacyComparer {
        
        // CODEGEN: Generating message contract since element name sDomain from namespace http://workshare.com/compareservices/1.1/comparewebservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/1.1/comparewebservice/Authenticate", ReplyAction="http://workshare.com/compareservices/1.1/comparewebservice/AuthenticateResponse")]
        Document.Services.Compare.Control.ComparerProxy.AuthenticateResponse1 Authenticate(Document.Services.Compare.Control.ComparerProxy.AuthenticateRequest1 request);
        
        // CODEGEN: Generating message contract since element name compareOptions from namespace http://workshare.com/compareservices/1.1/comparewebservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/1.1/comparewebservice/Execute", ReplyAction="http://workshare.com/compareservices/1.1/comparewebservice/ExecuteResponse")]
        Document.Services.Compare.Control.ComparerProxy.ExecuteResponse Execute(Document.Services.Compare.Control.ComparerProxy.ExecuteRequest request);
        
        // CODEGEN: Generating message contract since element name original from namespace http://workshare.com/compareservices/1.1/comparewebservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/1.1/comparewebservice/Execute2", ReplyAction="http://workshare.com/compareservices/1.1/comparewebservice/Execute2Response")]
        Document.Services.Compare.Control.ComparerProxy.Execute2Response Execute2(Document.Services.Compare.Control.ComparerProxy.Execute2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authenticate", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/", Order=0)]
        public Document.Services.Compare.Control.ComparerProxy.AuthenticateRequest1Body Body;
        
        public AuthenticateRequest1() {
        }
        
        public AuthenticateRequest1(Document.Services.Compare.Control.ComparerProxy.AuthenticateRequest1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://workshare.com/compareservices/1.1/comparewebservice/")]
    public partial class AuthenticateRequest1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sDomain;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sPass;
        
        public AuthenticateRequest1Body() {
        }
        
        public AuthenticateRequest1Body(string sDomain, string sUser, string sPass) {
            this.sDomain = sDomain;
            this.sUser = sUser;
            this.sPass = sPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateResponse", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/", Order=0)]
        public Document.Services.Compare.Control.ComparerProxy.AuthenticateResponse1Body Body;
        
        public AuthenticateResponse1() {
        }
        
        public AuthenticateResponse1(Document.Services.Compare.Control.ComparerProxy.AuthenticateResponse1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://workshare.com/compareservices/1.1/comparewebservice/")]
    public partial class AuthenticateResponse1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AuthenticateResult;
        
        public AuthenticateResponse1Body() {
        }
        
        public AuthenticateResponse1Body(bool AuthenticateResult) {
            this.AuthenticateResult = AuthenticateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/", Order=0)]
        public Document.Services.Compare.Control.ComparerProxy.ExecuteRequestBody Body;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(Document.Services.Compare.Control.ComparerProxy.ExecuteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://workshare.com/compareservices/1.1/comparewebservice/")]
    public partial class ExecuteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public Document.Services.Compare.Control.ComparerProxy.CompareResponseFlags flags;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string compareOptions;
        
        public ExecuteRequestBody() {
        }
        
        public ExecuteRequestBody(Document.Services.Compare.Control.ComparerProxy.CompareResponseFlags flags, string compareOptions) {
            this.flags = flags;
            this.compareOptions = compareOptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteResponse", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/", Order=0)]
        public Document.Services.Compare.Control.ComparerProxy.ExecuteResponseBody Body;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(Document.Services.Compare.Control.ComparerProxy.ExecuteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ExecuteResponseBody {
        
        public ExecuteResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute2", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/", Order=0)]
        public Document.Services.Compare.Control.ComparerProxy.Execute2RequestBody Body;
        
        public Execute2Request() {
        }
        
        public Execute2Request(Document.Services.Compare.Control.ComparerProxy.Execute2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://workshare.com/compareservices/1.1/comparewebservice/")]
    public partial class Execute2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] original;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] modified;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Document.Services.Compare.Control.ComparerProxy.CompareResponseFlags flags;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string compareOptions;
        
        public Execute2RequestBody() {
        }
        
        public Execute2RequestBody(byte[] original, byte[] modified, Document.Services.Compare.Control.ComparerProxy.CompareResponseFlags flags, string compareOptions) {
            this.original = original;
            this.modified = modified;
            this.flags = flags;
            this.compareOptions = compareOptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute2Response", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/", Order=0)]
        public Document.Services.Compare.Control.ComparerProxy.Execute2ResponseBody Body;
        
        public Execute2Response() {
        }
        
        public Execute2Response(Document.Services.Compare.Control.ComparerProxy.Execute2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://workshare.com/compareservices/1.1/comparewebservice/")]
    public partial class Execute2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Document.Services.Compare.Control.ComparerProxy.CompareResult Execute2Result;
        
        public Execute2ResponseBody() {
        }
        
        public Execute2ResponseBody(Document.Services.Compare.Control.ComparerProxy.CompareResult Execute2Result) {
            this.Execute2Result = Execute2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ILegacyComparerChannel : Document.Services.Compare.Control.ComparerProxy.ILegacyComparer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class LegacyComparerClient : System.ServiceModel.ClientBase<Document.Services.Compare.Control.ComparerProxy.ILegacyComparer>, Document.Services.Compare.Control.ComparerProxy.ILegacyComparer {
        
        public LegacyComparerClient() {
        }
        
        public LegacyComparerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LegacyComparerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LegacyComparerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LegacyComparerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Document.Services.Compare.Control.ComparerProxy.AuthenticateResponse1 Document.Services.Compare.Control.ComparerProxy.ILegacyComparer.Authenticate(Document.Services.Compare.Control.ComparerProxy.AuthenticateRequest1 request) {
            return base.Channel.Authenticate(request);
        }
        
        public bool Authenticate(string sDomain, string sUser, string sPass) {
            Document.Services.Compare.Control.ComparerProxy.AuthenticateRequest1 inValue = new Document.Services.Compare.Control.ComparerProxy.AuthenticateRequest1();
            inValue.Body = new Document.Services.Compare.Control.ComparerProxy.AuthenticateRequest1Body();
            inValue.Body.sDomain = sDomain;
            inValue.Body.sUser = sUser;
            inValue.Body.sPass = sPass;
            Document.Services.Compare.Control.ComparerProxy.AuthenticateResponse1 retVal = ((Document.Services.Compare.Control.ComparerProxy.ILegacyComparer)(this)).Authenticate(inValue);
            return retVal.Body.AuthenticateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Document.Services.Compare.Control.ComparerProxy.ExecuteResponse Document.Services.Compare.Control.ComparerProxy.ILegacyComparer.Execute(Document.Services.Compare.Control.ComparerProxy.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public void Execute(Document.Services.Compare.Control.ComparerProxy.CompareResponseFlags flags, string compareOptions) {
            Document.Services.Compare.Control.ComparerProxy.ExecuteRequest inValue = new Document.Services.Compare.Control.ComparerProxy.ExecuteRequest();
            inValue.Body = new Document.Services.Compare.Control.ComparerProxy.ExecuteRequestBody();
            inValue.Body.flags = flags;
            inValue.Body.compareOptions = compareOptions;
            Document.Services.Compare.Control.ComparerProxy.ExecuteResponse retVal = ((Document.Services.Compare.Control.ComparerProxy.ILegacyComparer)(this)).Execute(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Document.Services.Compare.Control.ComparerProxy.Execute2Response Document.Services.Compare.Control.ComparerProxy.ILegacyComparer.Execute2(Document.Services.Compare.Control.ComparerProxy.Execute2Request request) {
            return base.Channel.Execute2(request);
        }
        
        public Document.Services.Compare.Control.ComparerProxy.CompareResult Execute2(byte[] original, byte[] modified, Document.Services.Compare.Control.ComparerProxy.CompareResponseFlags flags, string compareOptions) {
            Document.Services.Compare.Control.ComparerProxy.Execute2Request inValue = new Document.Services.Compare.Control.ComparerProxy.Execute2Request();
            inValue.Body = new Document.Services.Compare.Control.ComparerProxy.Execute2RequestBody();
            inValue.Body.original = original;
            inValue.Body.modified = modified;
            inValue.Body.flags = flags;
            inValue.Body.compareOptions = compareOptions;
            Document.Services.Compare.Control.ComparerProxy.Execute2Response retVal = ((Document.Services.Compare.Control.ComparerProxy.ILegacyComparer)(this)).Execute2(inValue);
            return retVal.Body.Execute2Result;
        }
    }
}
