using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2300
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------



[assembly: AssemblyTitleAttribute("LocalFilestoreCompareQEventHandler")]
[assembly: GuidAttribute("C9B131B5-7FA0-4687-92E3-93E6A8A07DDE")]
