
package com.workshare.compareservices._5_2.comparewebservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-07-30T11:35:09.728+01:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "string", targetNamespace = "http://schemas.microsoft.com/2003/10/Serialization/")
public class IComparerChunkedInitialiseFileStringFaultFaultMessage extends Exception {
    
    private java.lang.String string;

    public IComparerChunkedInitialiseFileStringFaultFaultMessage() {
        super();
    }
    
    public IComparerChunkedInitialiseFileStringFaultFaultMessage(String message) {
        super(message);
    }
    
    public IComparerChunkedInitialiseFileStringFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IComparerChunkedInitialiseFileStringFaultFaultMessage(String message, java.lang.String string) {
        super(message);
        this.string = string;
    }

    public IComparerChunkedInitialiseFileStringFaultFaultMessage(String message, java.lang.String string, Throwable cause) {
        super(message, cause);
        this.string = string;
    }

    public java.lang.String getFaultInfo() {
        return this.string;
    }
}
