package com.workshare.compareservices._5_2.comparewebservice;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-07-30T11:35:09.812+01:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/", name = "IComparerChunked")
@XmlSeeAlso({com.workshare.compareservices._1_1.comparewebservice.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, com.workshare.compareservices._5_0.comparewebservice.ObjectFactory.class, ObjectFactory.class})
public interface IComparerChunked {

    @WebMethod(operationName = "AppendFile", action = "http://workshare.com/compareservices/5.2/comparewebservice/AppendOriginalFile")
    @Action(input = "http://workshare.com/compareservices/5.2/comparewebservice/AppendOriginalFile", output = "http://workshare.com/compareservices/5.2/comparewebservice/AppendOriginalFileResponse", fault = {@FaultAction(className = IComparerChunkedAppendFileStringFaultFaultMessage.class, value = "http://workshare.com/compareservices/5.2/comparewebservice/IComparerChunked/AppendFileStringFault")})
    @RequestWrapper(localName = "AppendFile", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/", className = "com.workshare.compareservices._5_2.comparewebservice.AppendFile")
    @ResponseWrapper(localName = "AppendFileResponse", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/", className = "com.workshare.compareservices._5_2.comparewebservice.AppendFileResponse")
    public void appendFile(
        @WebParam(name = "guidFile", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/")
        java.lang.String guidFile,
        @WebParam(name = "fileChunk", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/")
        byte[] fileChunk,
        @WebParam(name = "previousBytesSent", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/")
        java.lang.Long previousBytesSent
    ) throws IComparerChunkedAppendFileStringFaultFaultMessage;

    @WebMethod(operationName = "Authenticate", action = "http://workshare.com/compareservices/5.0/comparewebservice/Authenticate")
    @Action(input = "http://workshare.com/compareservices/5.0/comparewebservice/Authenticate", output = "http://workshare.com/compareservices/5.0/comparewebservice/AuthenticateResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void authenticate();

    @WebMethod(operationName = "SetOptionsSet", action = "http://workshare.com/compareservices/5.0/comparewebservice/SetOptionsSet")
    @Action(input = "http://workshare.com/compareservices/5.0/comparewebservice/SetOptionsSet", output = "http://workshare.com/compareservices/5.0/comparewebservice/SetOptionsSetResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void setOptionsSet();

    @WebMethod(operationName = "GetVersion", action = "http://workshare.com/compareservices/5.0/comparewebservice/GetVersion")
    @Action(input = "http://workshare.com/compareservices/5.0/comparewebservice/GetVersion", output = "http://workshare.com/compareservices/5.0/comparewebservice/GetVersionResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void getVersion();

    @WebMethod(operationName = "GetOptionsSet", action = "http://workshare.com/compareservices/5.0/comparewebservice/GetOptionsSet")
    @Action(input = "http://workshare.com/compareservices/5.0/comparewebservice/GetOptionsSet", output = "http://workshare.com/compareservices/5.0/comparewebservice/GetOptionsSetResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void getOptionsSet();

    @WebMethod(operationName = "ReleaseFile", action = "http://workshare.com/compareservices/5.2/comparewebservice/ReleaseFile")
    @Action(input = "http://workshare.com/compareservices/5.2/comparewebservice/ReleaseFile", output = "http://workshare.com/compareservices/5.2/comparewebservice/ReleaseFileResponse", fault = {@FaultAction(className = IComparerChunkedReleaseFileStringFaultFaultMessage.class, value = "http://workshare.com/compareservices/5.2/comparewebservice/IComparerChunked/ReleaseFileStringFault")})
    @RequestWrapper(localName = "ReleaseFile", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/", className = "com.workshare.compareservices._5_2.comparewebservice.ReleaseFile")
    @ResponseWrapper(localName = "ReleaseFileResponse", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/", className = "com.workshare.compareservices._5_2.comparewebservice.ReleaseFileResponse")
    public void releaseFile(
        @WebParam(name = "fileGuid", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/")
        java.lang.String fileGuid
    ) throws IComparerChunkedReleaseFileStringFaultFaultMessage;

    @WebMethod(operationName = "ReleaseAll", action = "http://workshare.com/compareservices/5.2/comparewebservice/ReleaseAll")
    @Action(input = "http://workshare.com/compareservices/5.2/comparewebservice/ReleaseAll")
    @Oneway
    @RequestWrapper(localName = "ReleaseAll", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/", className = "com.workshare.compareservices._5_2.comparewebservice.ReleaseAll")
    public void releaseAll();

    @WebMethod(operationName = "Benchmark", action = "http://workshare.com/compareservices/5.2/comparewebservice/Benchmark")
    @Action(input = "http://workshare.com/compareservices/5.2/comparewebservice/Benchmark", output = "http://workshare.com/compareservices/5.2/comparewebservice/BenchmarkResponse", fault = {@FaultAction(className = IComparerChunkedBenchmarkStringFaultFaultMessage.class, value = "http://workshare.com/compareservices/5.2/comparewebservice/IComparerChunked/BenchmarkStringFault")})
    @RequestWrapper(localName = "Benchmark", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/", className = "com.workshare.compareservices._5_2.comparewebservice.Benchmark")
    @ResponseWrapper(localName = "BenchmarkResponse", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/", className = "com.workshare.compareservices._5_2.comparewebservice.BenchmarkResponse")
    @WebResult(name = "BenchmarkResult", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/")
    public com.workshare.compareservices._5_2.comparewebservice.PerformanceResults benchmark(
        @WebParam(name = "guidOriginalFile", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/")
        java.lang.String guidOriginalFile,
        @WebParam(name = "guidModifiedFile", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/")
        java.lang.String guidModifiedFile,
        @WebParam(name = "ResponseOption", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/")
        com.workshare.compareservices._5_0.comparewebservice.ResponseOptions responseOption,
        @WebParam(name = "CompareOptions", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/")
        java.lang.String compareOptions
    ) throws IComparerChunkedBenchmarkStringFaultFaultMessage;

    @WebMethod(operationName = "Compare", action = "http://workshare.com/compareservices/5.2/comparewebservice/Compare")
    @Action(input = "http://workshare.com/compareservices/5.2/comparewebservice/Compare", output = "http://workshare.com/compareservices/5.2/comparewebservice/CompareResponse", fault = {@FaultAction(className = IComparerChunkedCompareStringFaultFaultMessage.class, value = "http://workshare.com/compareservices/5.2/comparewebservice/IComparerChunked/CompareStringFault")})
    @RequestWrapper(localName = "Compare", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/", className = "com.workshare.compareservices._5_2.comparewebservice.Compare")
    @ResponseWrapper(localName = "CompareResponse", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/", className = "com.workshare.compareservices._5_2.comparewebservice.CompareResponse")
    @WebResult(name = "CompareResult", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/")
    public com.workshare.compareservices._5_0.comparewebservice.CompareResults compare(
        @WebParam(name = "guidOriginalFile", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/")
        java.lang.String guidOriginalFile,
        @WebParam(name = "guidModifiedFile", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/")
        java.lang.String guidModifiedFile,
        @WebParam(name = "ResponseOption", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/")
        com.workshare.compareservices._5_0.comparewebservice.ResponseOptions responseOption,
        @WebParam(name = "CompareOptions", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/")
        java.lang.String compareOptions
    ) throws IComparerChunkedCompareStringFaultFaultMessage;

    @WebMethod(operationName = "InitialiseFile", action = "http://workshare.com/compareservices/5.2/comparewebservice/InitialiseFile")
    @Action(input = "http://workshare.com/compareservices/5.2/comparewebservice/InitialiseFile", output = "http://workshare.com/compareservices/5.2/comparewebservice/InitialiseFileResponse", fault = {@FaultAction(className = IComparerChunkedInitialiseFileStringFaultFaultMessage.class, value = "http://workshare.com/compareservices/5.2/comparewebservice/IComparerChunked/InitialiseFileStringFault")})
    @RequestWrapper(localName = "InitialiseFile", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/", className = "com.workshare.compareservices._5_2.comparewebservice.InitialiseFile")
    @ResponseWrapper(localName = "InitialiseFileResponse", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/", className = "com.workshare.compareservices._5_2.comparewebservice.InitialiseFileResponse")
    @WebResult(name = "InitialiseFileResult", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/")
    public java.lang.String initialiseFile(
        @WebParam(name = "fileID", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/")
        java.lang.String fileID,
        @WebParam(name = "sizeBytes", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/")
        java.lang.Long sizeBytes
    ) throws IComparerChunkedInitialiseFileStringFaultFaultMessage;

    @WebMethod(operationName = "CompareEx", action = "http://workshare.com/compareservices/5.2/comparewebservice/CompareEx")
    @Action(input = "http://workshare.com/compareservices/5.2/comparewebservice/CompareEx", output = "http://workshare.com/compareservices/5.2/comparewebservice/CompareExResponse", fault = {@FaultAction(className = IComparerChunkedCompareExStringFaultFaultMessage.class, value = "http://workshare.com/compareservices/5.2/comparewebservice/IComparerChunked/CompareExStringFault")})
    @RequestWrapper(localName = "CompareEx", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/", className = "com.workshare.compareservices._5_2.comparewebservice.CompareEx")
    @ResponseWrapper(localName = "CompareExResponse", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/", className = "com.workshare.compareservices._5_2.comparewebservice.CompareExResponse")
    @WebResult(name = "CompareExResult", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/")
    public com.workshare.compareservices._5_0.comparewebservice.CompareResults compareEx(
        @WebParam(name = "executeParams", targetNamespace = "http://workshare.com/compareservices/5.2/comparewebservice/")
        com.workshare.compareservices._5_0.comparewebservice.ChunkedExecuteParams executeParams
    ) throws IComparerChunkedCompareExStringFaultFaultMessage;

    @WebMethod(operationName = "GetCompositorVersion", action = "http://workshare.com/compareservices/5.0/comparewebservice/GetCompositorVersion")
    @Action(input = "http://workshare.com/compareservices/5.0/comparewebservice/GetCompositorVersion", output = "http://workshare.com/compareservices/5.0/comparewebservice/GetCompositorVersionResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void getCompositorVersion();
}
