//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1366
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workshare.Document.Services.Compare.MSMQSample.CompareMSMQProxy
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", ConfigurationName="Workshare.Document.Services.Compare.MSMQSample.CompareMSMQProxy.IComparerQueued")]
    public interface IComparerQueued
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://workshare.com/compareservices/5.0/comparewebservice/ExecuteQueued")]
        void ExecuteQueued(System.Collections.Generic.Dictionary<string, string> dicQueueParams);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://workshare.com/compareservices/5.0/comparewebservice/ExecuteQueuedCustom")]
        void ExecuteQueuedCustom(System.Collections.Generic.Dictionary<string, string> dicQueueParams, string sCustomHandler);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IComparerQueuedChannel : Workshare.Document.Services.Compare.MSMQSample.CompareMSMQProxy.IComparerQueued, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ComparerQueuedClient : System.ServiceModel.ClientBase<Workshare.Document.Services.Compare.MSMQSample.CompareMSMQProxy.IComparerQueued>, Workshare.Document.Services.Compare.MSMQSample.CompareMSMQProxy.IComparerQueued
    {
        
        public ComparerQueuedClient()
        {
        }
        
        public ComparerQueuedClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ComparerQueuedClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ComparerQueuedClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ComparerQueuedClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void ExecuteQueued(System.Collections.Generic.Dictionary<string, string> dicQueueParams)
        {
            base.Channel.ExecuteQueued(dicQueueParams);
        }
        
        public void ExecuteQueuedCustom(System.Collections.Generic.Dictionary<string, string> dicQueueParams, string sCustomHandler)
        {
            base.Channel.ExecuteQueuedCustom(dicQueueParams, sCustomHandler);
        }
    }
}
