
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.workshare.compareservices._5_0.comparewebservice;

import java.net.URL;
import java.util.logging.Logger;

import com.workshare.compareservices._1_1.comparewebservice.Comparer;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-07-30T11:35:09.757+01:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "Comparer",
                      portName = "CompareWebServiceWCF",
                      targetNamespace = "http://workshare.com/compareservices/1.1/comparewebservice/",
                      wsdlLocation = "http://localhost:8080/Comparer?wsdl",
                      endpointInterface = "com.workshare.compareservices._5_0.comparewebservice.IComparer")
                      
public class CompareWebServiceWCFImpl implements IComparer {

    private static final Logger LOG = Logger.getLogger(CompareWebServiceWCFImpl.class.getName());
    private Comparer service ; 
    private IComparer port;  
    
    public CompareWebServiceWCFImpl() {
    	service = new Comparer(Comparer.WSDL_LOCATION,  Comparer.SERVICE);
    	port = service.getCompareWebServiceWCF();
    }

    public CompareWebServiceWCFImpl(Comparer service) {
		super();
		this.service = service;
		this.port = service.getCompareWebServiceWCF();
	}
    
    public CompareWebServiceWCFImpl(URL wsdlLocation){
    	super();
    	service = new Comparer(wsdlLocation);
    	port = service.getCompareWebServiceWCF();
    }
    

	/* (non-Javadoc)
     * @see com.workshare.compareservices._5_0.comparewebservice.IComparer#getCompositorVersion(*
     */
    public java.lang.String getCompositorVersion() { 
        LOG.info("Executing operation getCompositorVersion");
        try {
            java.lang.String _return = port.getCompositorVersion();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.workshare.compareservices._5_0.comparewebservice.IComparer#executeEx(com.workshare.compareservices._5_0.comparewebservice.ExecuteParams  execParams )*
     */
    public com.workshare.compareservices._5_0.comparewebservice.CompareResults executeEx(com.workshare.compareservices._5_0.comparewebservice.ExecuteParams execParams) { 
        LOG.info("Executing operation executeEx");
        System.out.println(execParams);
        try {
            com.workshare.compareservices._5_0.comparewebservice.CompareResults _return = port.executeEx(execParams); 
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.workshare.compareservices._5_0.comparewebservice.IComparer#setOptionsSet(java.lang.String  sOptionsSet )*
     */
    public java.lang.Boolean setOptionsSet(java.lang.String sOptionsSet) { 
        LOG.info("Executing operation setOptionsSet");
        System.out.println(sOptionsSet);
        try {
            java.lang.Boolean _return = port.setOptionsSet(sOptionsSet); 
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.workshare.compareservices._5_0.comparewebservice.IComparer#ping(*
     */
    public com.workshare.compareservices._5_0.comparewebservice.CompareResults ping() { 
        LOG.info("Executing operation ping");
        try {
            com.workshare.compareservices._5_0.comparewebservice.CompareResults _return = port.ping(); 
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.workshare.compareservices._5_0.comparewebservice.IComparer#getVersion(*
     */
    public java.lang.String getVersion() { 
        LOG.info("Executing operation getVersion");
        try {
            java.lang.String _return = port.getVersion() ;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.workshare.compareservices._5_0.comparewebservice.IComparer#getOptionsSet(*
     */
    public java.lang.String getOptionsSet() { 
        LOG.info("Executing operation getOptionsSet");
        try {
            java.lang.String _return = port.getOptionsSet() ;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.workshare.compareservices._5_0.comparewebservice.IComparer#authenticate(java.lang.String  sRealm ,)java.lang.String  sUser ,)java.lang.String  sPassword )*
     */
    public java.lang.Boolean authenticate(java.lang.String sRealm,java.lang.String sUser,java.lang.String sPassword) { 
        LOG.info("Executing operation authenticate");
        System.out.println(sRealm);
        System.out.println(sUser);
        System.out.println(sPassword);
        try {
            java.lang.Boolean _return = port.authenticate(sRealm, sUser, sPassword) ;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.workshare.compareservices._5_0.comparewebservice.IComparer#execute(byte[]  originalData ,)byte[]  modifiedData ,)com.workshare.compareservices._5_0.comparewebservice.ResponseOptions  responseOption ,)java.lang.String  compareOptions )*
     */
    public com.workshare.compareservices._5_0.comparewebservice.CompareResults execute(byte[] originalData,byte[] modifiedData,com.workshare.compareservices._5_0.comparewebservice.ResponseOptions responseOption,java.lang.String compareOptions) { 
        LOG.info("Executing operation execute");
        System.out.println(originalData);
        System.out.println(modifiedData);
        System.out.println(responseOption);
        System.out.println(compareOptions);
        try {
            com.workshare.compareservices._5_0.comparewebservice.CompareResults _return = port.execute(originalData, modifiedData, responseOption, compareOptions); 
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
