package com.workshare.compareservices._5_0.comparewebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-07-30T11:35:09.804+01:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/", name = "IComparer")
@XmlSeeAlso({com.workshare.compareservices._1_1.comparewebservice.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, com.workshare.compareservices._5_2.comparewebservice.ObjectFactory.class})
public interface IComparer {

    @WebMethod(operationName = "GetCompositorVersion", action = "http://workshare.com/compareservices/5.0/comparewebservice/GetCompositorVersion")
    @Action(input = "http://workshare.com/compareservices/5.0/comparewebservice/GetCompositorVersion", output = "http://workshare.com/compareservices/5.0/comparewebservice/GetCompositorVersionResponse")
    @RequestWrapper(localName = "GetCompositorVersion", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/", className = "com.workshare.compareservices._5_0.comparewebservice.GetCompositorVersion")
    @ResponseWrapper(localName = "GetCompositorVersionResponse", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/", className = "com.workshare.compareservices._5_0.comparewebservice.GetCompositorVersionResponse")
    @WebResult(name = "GetCompositorVersionResult", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/")
    public java.lang.String getCompositorVersion();

    @WebMethod(operationName = "ExecuteEx", action = "http://workshare.com/compareservices/5.0/comparewebservice/ExecuteEx")
    @Action(input = "http://workshare.com/compareservices/5.0/comparewebservice/ExecuteEx", output = "http://workshare.com/compareservices/5.0/comparewebservice/ExecuteExResponse")
    @RequestWrapper(localName = "ExecuteEx", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/", className = "com.workshare.compareservices._5_0.comparewebservice.ExecuteEx")
    @ResponseWrapper(localName = "ExecuteExResponse", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/", className = "com.workshare.compareservices._5_0.comparewebservice.ExecuteExResponse")
    @WebResult(name = "ExecuteExResult", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/")
    public com.workshare.compareservices._5_0.comparewebservice.CompareResults executeEx(
        @WebParam(name = "execParams", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/")
        com.workshare.compareservices._5_0.comparewebservice.ExecuteParams execParams
    );

    @WebMethod(operationName = "SetOptionsSet", action = "http://workshare.com/compareservices/5.0/comparewebservice/SetOptionsSet")
    @Action(input = "http://workshare.com/compareservices/5.0/comparewebservice/SetOptionsSet", output = "http://workshare.com/compareservices/5.0/comparewebservice/SetOptionsSetResponse")
    @RequestWrapper(localName = "SetOptionsSet", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/", className = "com.workshare.compareservices._5_0.comparewebservice.SetOptionsSet")
    @ResponseWrapper(localName = "SetOptionsSetResponse", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/", className = "com.workshare.compareservices._5_0.comparewebservice.SetOptionsSetResponse")
    @WebResult(name = "SetOptionsSetResult", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/")
    public java.lang.Boolean setOptionsSet(
        @WebParam(name = "sOptionsSet", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/")
        java.lang.String sOptionsSet
    );

    @WebMethod(operationName = "Ping", action = "http://workshare.com/compareservices/5.0/comparewebservice/Ping")
    @Action(input = "http://workshare.com/compareservices/5.0/comparewebservice/Ping", output = "http://workshare.com/compareservices/5.0/comparewebservice/PingResponse")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/", className = "com.workshare.compareservices._5_0.comparewebservice.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/", className = "com.workshare.compareservices._5_0.comparewebservice.PingResponse")
    @WebResult(name = "PingResult", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/")
    public com.workshare.compareservices._5_0.comparewebservice.CompareResults ping();

    @WebMethod(operationName = "GetVersion", action = "http://workshare.com/compareservices/5.0/comparewebservice/GetVersion")
    @Action(input = "http://workshare.com/compareservices/5.0/comparewebservice/GetVersion", output = "http://workshare.com/compareservices/5.0/comparewebservice/GetVersionResponse")
    @RequestWrapper(localName = "GetVersion", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/", className = "com.workshare.compareservices._5_0.comparewebservice.GetVersion")
    @ResponseWrapper(localName = "GetVersionResponse", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/", className = "com.workshare.compareservices._5_0.comparewebservice.GetVersionResponse")
    @WebResult(name = "GetVersionResult", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/")
    public java.lang.String getVersion();

    @WebMethod(operationName = "GetOptionsSet", action = "http://workshare.com/compareservices/5.0/comparewebservice/GetOptionsSet")
    @Action(input = "http://workshare.com/compareservices/5.0/comparewebservice/GetOptionsSet", output = "http://workshare.com/compareservices/5.0/comparewebservice/GetOptionsSetResponse")
    @RequestWrapper(localName = "GetOptionsSet", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/", className = "com.workshare.compareservices._5_0.comparewebservice.GetOptionsSet")
    @ResponseWrapper(localName = "GetOptionsSetResponse", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/", className = "com.workshare.compareservices._5_0.comparewebservice.GetOptionsSetResponse")
    @WebResult(name = "GetOptionsSetResult", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/")
    public java.lang.String getOptionsSet();

    @WebMethod(operationName = "Authenticate", action = "http://workshare.com/compareservices/5.0/comparewebservice/Authenticate")
    @Action(input = "http://workshare.com/compareservices/5.0/comparewebservice/Authenticate", output = "http://workshare.com/compareservices/5.0/comparewebservice/AuthenticateResponse")
    @RequestWrapper(localName = "Authenticate", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/", className = "com.workshare.compareservices._5_0.comparewebservice.Authenticate")
    @ResponseWrapper(localName = "AuthenticateResponse", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/", className = "com.workshare.compareservices._5_0.comparewebservice.AuthenticateResponse")
    @WebResult(name = "AuthenticateResult", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/")
    public java.lang.Boolean authenticate(
        @WebParam(name = "sRealm", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/")
        java.lang.String sRealm,
        @WebParam(name = "sUser", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/")
        java.lang.String sUser,
        @WebParam(name = "sPassword", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/")
        java.lang.String sPassword
    );

    @WebMethod(operationName = "Execute", action = "http://workshare.com/compareservices/5.0/comparewebservice/Execute")
    @Action(input = "http://workshare.com/compareservices/5.0/comparewebservice/Execute", output = "http://workshare.com/compareservices/5.0/comparewebservice/ExecuteResponse")
    @RequestWrapper(localName = "Execute", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/", className = "com.workshare.compareservices._5_0.comparewebservice.Execute")
    @ResponseWrapper(localName = "ExecuteResponse", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/", className = "com.workshare.compareservices._5_0.comparewebservice.ExecuteResponse")
    @WebResult(name = "ExecuteResult", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/")
    public com.workshare.compareservices._5_0.comparewebservice.CompareResults execute(
        @WebParam(name = "OriginalData", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/")
        byte[] originalData,
        @WebParam(name = "ModifiedData", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/")
        byte[] modifiedData,
        @WebParam(name = "ResponseOption", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/")
        com.workshare.compareservices._5_0.comparewebservice.ResponseOptions responseOption,
        @WebParam(name = "CompareOptions", targetNamespace = "http://workshare.com/compareservices/5.0/comparewebservice/")
        java.lang.String compareOptions
    );
}
