
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.workshare.compareservices._1_1.comparewebservice;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-07-30T11:35:09.741+01:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "Comparer",
                      portName = "CompareWebServiceSoap",
                      targetNamespace = "http://workshare.com/compareservices/1.1/comparewebservice/",
                      wsdlLocation = "http://localhost:8080/Comparer?wsdl",
                      endpointInterface = "com.workshare.compareservices._1_1.comparewebservice.ILegacyComparer")
                      
public class CompareWebServiceSoapImpl implements ILegacyComparer {

    private static final Logger LOG = Logger.getLogger(CompareWebServiceSoapImpl.class.getName());
    Comparer service = new Comparer(Comparer.WSDL_LOCATION,  Comparer.SERVICE);
    ILegacyComparer port = service.getCompareWebServiceSoap();
    
    /* (non-Javadoc)
     * @see com.workshare.compareservices._1_1.comparewebservice.ILegacyComparer#execute2(byte[]  original ,)byte[]  modified ,)com.workshare.compareservices._1_1.comparewebservice.CompareResponseFlags  flags ,)java.lang.String  compareOptions )*
     */
    public com.workshare.compareservices._1_1.comparewebservice.CompareResult execute2(byte[] original,byte[] modified,com.workshare.compareservices._1_1.comparewebservice.CompareResponseFlags flags,java.lang.String compareOptions) { 
        LOG.info("Executing operation execute2");
        System.out.println(original);
        System.out.println(modified);
        System.out.println(flags);
        System.out.println(compareOptions);
        try {

            com.workshare.compareservices._1_1.comparewebservice.CompareResult _return = port.execute2(original, modified, flags, compareOptions) ;  
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.workshare.compareservices._1_1.comparewebservice.ILegacyComparer#authenticate(java.lang.String  sDomain ,)java.lang.String  sUser ,)java.lang.String  sPass )*
     */
    public boolean authenticate(java.lang.String sDomain,java.lang.String sUser,java.lang.String sPass) { 
        LOG.info("Executing operation authenticate");
        System.out.println(sDomain);
        System.out.println(sUser);
        System.out.println(sPass);
        try {
            boolean _return=port.authenticate(sDomain, sUser, sPass);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.workshare.compareservices._1_1.comparewebservice.ILegacyComparer#execute(com.workshare.compareservices._1_1.comparewebservice.CompareResponseFlags  flags ,)java.lang.String  compareOptions )*
     */
    public void execute(com.workshare.compareservices._1_1.comparewebservice.CompareResponseFlags flags,java.lang.String compareOptions) { 
        LOG.info("Executing operation execute");
        System.out.println(flags);
        System.out.println(compareOptions);
        try {
        	port.execute(flags, compareOptions);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
