package com.workshare.compareservices._1_1.comparewebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-07-30T11:35:09.796+01:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://workshare.com/compareservices/1.1/comparewebservice/", name = "ILegacyComparer")
@XmlSeeAlso({ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, com.workshare.compareservices._5_0.comparewebservice.ObjectFactory.class, com.workshare.compareservices._5_2.comparewebservice.ObjectFactory.class})
public interface ILegacyComparer {

    @WebMethod(operationName = "Execute2", action = "http://workshare.com/compareservices/1.1/comparewebservice/Execute2")
    @Action(input = "http://workshare.com/compareservices/1.1/comparewebservice/Execute2", output = "http://workshare.com/compareservices/1.1/comparewebservice/Execute2Response")
    @RequestWrapper(localName = "Execute2", targetNamespace = "http://workshare.com/compareservices/1.1/comparewebservice/", className = "com.workshare.compareservices._1_1.comparewebservice.Execute2")
    @ResponseWrapper(localName = "Execute2Response", targetNamespace = "http://workshare.com/compareservices/1.1/comparewebservice/", className = "com.workshare.compareservices._1_1.comparewebservice.Execute2Response")
    @WebResult(name = "Execute2Result", targetNamespace = "http://workshare.com/compareservices/1.1/comparewebservice/")
    public com.workshare.compareservices._1_1.comparewebservice.CompareResult execute2(
        @WebParam(name = "original", targetNamespace = "http://workshare.com/compareservices/1.1/comparewebservice/")
        byte[] original,
        @WebParam(name = "modified", targetNamespace = "http://workshare.com/compareservices/1.1/comparewebservice/")
        byte[] modified,
        @WebParam(name = "flags", targetNamespace = "http://workshare.com/compareservices/1.1/comparewebservice/")
        com.workshare.compareservices._1_1.comparewebservice.CompareResponseFlags flags,
        @WebParam(name = "compareOptions", targetNamespace = "http://workshare.com/compareservices/1.1/comparewebservice/")
        java.lang.String compareOptions
    );

    @WebMethod(operationName = "Authenticate", action = "http://workshare.com/compareservices/1.1/comparewebservice/Authenticate")
    @Action(input = "http://workshare.com/compareservices/1.1/comparewebservice/Authenticate", output = "http://workshare.com/compareservices/1.1/comparewebservice/AuthenticateResponse")
    @RequestWrapper(localName = "Authenticate", targetNamespace = "http://workshare.com/compareservices/1.1/comparewebservice/", className = "com.workshare.compareservices._1_1.comparewebservice.Authenticate")
    @ResponseWrapper(localName = "AuthenticateResponse", targetNamespace = "http://workshare.com/compareservices/1.1/comparewebservice/", className = "com.workshare.compareservices._1_1.comparewebservice.AuthenticateResponse")
    @WebResult(name = "AuthenticateResult", targetNamespace = "http://workshare.com/compareservices/1.1/comparewebservice/")
    public boolean authenticate(
        @WebParam(name = "sDomain", targetNamespace = "http://workshare.com/compareservices/1.1/comparewebservice/")
        java.lang.String sDomain,
        @WebParam(name = "sUser", targetNamespace = "http://workshare.com/compareservices/1.1/comparewebservice/")
        java.lang.String sUser,
        @WebParam(name = "sPass", targetNamespace = "http://workshare.com/compareservices/1.1/comparewebservice/")
        java.lang.String sPass
    );

    @WebMethod(operationName = "Execute", action = "http://workshare.com/compareservices/1.1/comparewebservice/Execute")
    @Action(input = "http://workshare.com/compareservices/1.1/comparewebservice/Execute", output = "http://workshare.com/compareservices/1.1/comparewebservice/ExecuteResponse")
    @RequestWrapper(localName = "Execute", targetNamespace = "http://workshare.com/compareservices/1.1/comparewebservice/", className = "com.workshare.compareservices._1_1.comparewebservice.Execute")
    @ResponseWrapper(localName = "ExecuteResponse", targetNamespace = "http://workshare.com/compareservices/1.1/comparewebservice/", className = "com.workshare.compareservices._1_1.comparewebservice.ExecuteResponse")
    public void execute(
        @WebParam(name = "flags", targetNamespace = "http://workshare.com/compareservices/1.1/comparewebservice/")
        com.workshare.compareservices._1_1.comparewebservice.CompareResponseFlags flags,
        @WebParam(name = "compareOptions", targetNamespace = "http://workshare.com/compareservices/1.1/comparewebservice/")
        java.lang.String compareOptions
    );
}
