//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workshare.Document.Services.Compare.Sample.CompareProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOptions", Namespace="http://workshare.com/compareservices/5.0/comparewebservice/")]
    public enum ResponseOptions : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rtf = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Xml = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RtfWithSummary = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wdf = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WdfWithSummary = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Doc = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DocWithSummary = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DocX = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DocXWithSummary = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pdf = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PdfWithSummary = 34,
        [EnumMember]
        RedlinMl = 0x40,
        [EnumMember]
        RedlinMlAndRtf = 0x41,
        [EnumMember]
        RedlinMlAndSummary = 0x42,
        [EnumMember]
        RedlinMlAndRtfAndSummary = 0x43,
        [EnumMember]
        RedlinMlAndDoc = 0x48,
        [EnumMember]
        RedlinMlAndDocAndSummary = 0x4A,
        [EnumMember]
        RedlinMlAndDocX = 0x50,
        [EnumMember]
        RedlinMlAndDocXAndSummary = 0x52,
        [EnumMember]
        RedlinMlAndPdf = 0x60,
        [EnumMember]
        RedlinMlAndPdfAndSummary = 0x62,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompareResults", Namespace="http://workshare.com/compareservices/5.0/comparewebservice/")]
    [System.SerializableAttribute()]
    public partial class CompareResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RedlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SummaryField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RedlineMlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Redline {
            get {
                return this.RedlineField;
            }
            set {
                if ((object.ReferenceEquals(this.RedlineField, value) != true)) {
                    this.RedlineField = value;
                    this.RaisePropertyChanged("Redline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary {
            get {
                return this.SummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryField, value) != true)) {
                    this.SummaryField = value;
                    this.RaisePropertyChanged("Summary");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RedlineMl
        {
            get
            {
                return this.RedlineMlField;
            }
            set
            {
                if( (object.ReferenceEquals(this.RedlineMlField, value) != true) )
                {
                    this.RedlineMlField = value;
                    this.RaisePropertyChanged("RedlineMl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecuteParams", Namespace="http://workshare.com/compareservices/5.0/comparewebservice/")]
    [System.SerializableAttribute()]
    public partial class ExecuteParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompareOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] OriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Workshare.Document.Services.Compare.Sample.CompareProxy.ResponseOptions ResponseOptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompareOptions {
            get {
                return this.CompareOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.CompareOptionsField, value) != true)) {
                    this.CompareOptionsField = value;
                    this.RaisePropertyChanged("CompareOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Modified {
            get {
                return this.ModifiedField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedField, value) != true)) {
                    this.ModifiedField = value;
                    this.RaisePropertyChanged("Modified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Original {
            get {
                return this.OriginalField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalField, value) != true)) {
                    this.OriginalField = value;
                    this.RaisePropertyChanged("Original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Workshare.Document.Services.Compare.Sample.CompareProxy.ResponseOptions ResponseOption {
            get {
                return this.ResponseOptionField;
            }
            set {
                if ((this.ResponseOptionField.Equals(value) != true)) {
                    this.ResponseOptionField = value;
                    this.RaisePropertyChanged("ResponseOption");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompareResponseFlags", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/")]
    public enum CompareResponseFlags : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rtf = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Xml = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Both = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompareResult", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/")]
    [System.SerializableAttribute()]
    public partial class CompareResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RedlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.XmlElement SummaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] Redline {
            get {
                return this.RedlineField;
            }
            set {
                if ((object.ReferenceEquals(this.RedlineField, value) != true)) {
                    this.RedlineField = value;
                    this.RaisePropertyChanged("Redline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Xml.XmlElement Summary {
            get {
                return this.SummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryField, value) != true)) {
                    this.SummaryField = value;
                    this.RaisePropertyChanged("Summary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", ConfigurationName="CompareProxy.IComparer")]
    public interface IComparer {

        [System.ServiceModel.OperationContractAttribute(ProtectionLevel = System.Net.Security.ProtectionLevel.EncryptAndSign, Action = "http://workshare.com/compareservices/5.0/comparewebservice/Authenticate", ReplyAction = "http://workshare.com/compareservices/5.0/comparewebservice/AuthenticateResponse")]
        bool Authenticate(string sRealm, string sUser, string sPassword);

        [System.ServiceModel.OperationContractAttribute(ProtectionLevel = System.Net.Security.ProtectionLevel.EncryptAndSign, Action = "http://workshare.com/compareservices/5.0/comparewebservice/GetVersion", ReplyAction = "http://workshare.com/compareservices/5.0/comparewebservice/GetVersionResponse")]
        string GetVersion();

        [System.ServiceModel.OperationContractAttribute(ProtectionLevel = System.Net.Security.ProtectionLevel.EncryptAndSign, Action = "http://workshare.com/compareservices/5.0/comparewebservice/GetCompositorVersion", ReplyAction = "http://workshare.com/compareservices/5.0/comparewebservice/GetCompositorVersionRe" +
            "sponse")]
        string GetCompositorVersion();

        [System.ServiceModel.OperationContractAttribute(ProtectionLevel = System.Net.Security.ProtectionLevel.EncryptAndSign, Action = "http://workshare.com/compareservices/5.0/comparewebservice/GetOptionsSet", ReplyAction = "http://workshare.com/compareservices/5.0/comparewebservice/GetOptionsSetResponse")]
        string GetOptionsSet();

        [System.ServiceModel.OperationContractAttribute(ProtectionLevel = System.Net.Security.ProtectionLevel.EncryptAndSign, Action = "http://workshare.com/compareservices/5.0/comparewebservice/SetOptionsSet", ReplyAction = "http://workshare.com/compareservices/5.0/comparewebservice/SetOptionsSetResponse")]
        bool SetOptionsSet(string sOptionsSet);

        [System.ServiceModel.OperationContractAttribute(ProtectionLevel = System.Net.Security.ProtectionLevel.EncryptAndSign, Action = "http://workshare.com/compareservices/5.0/comparewebservice/Execute", ReplyAction = "http://workshare.com/compareservices/5.0/comparewebservice/ExecuteResponse")]
        Workshare.Document.Services.Compare.Sample.CompareProxy.CompareResults Execute(byte[] OriginalData, byte[] ModifiedData, Workshare.Document.Services.Compare.Sample.CompareProxy.ResponseOptions ResponseOption, string CompareOptions);

        [System.ServiceModel.OperationContractAttribute(ProtectionLevel = System.Net.Security.ProtectionLevel.EncryptAndSign, Action = "http://workshare.com/compareservices/5.0/comparewebservice/ExecuteEx", ReplyAction = "http://workshare.com/compareservices/5.0/comparewebservice/ExecuteExResponse")]
        Workshare.Document.Services.Compare.Sample.CompareProxy.CompareResults ExecuteEx(Workshare.Document.Services.Compare.Sample.CompareProxy.ExecuteParams execParams);

        [System.ServiceModel.OperationContractAttribute(ProtectionLevel = System.Net.Security.ProtectionLevel.EncryptAndSign, Action = "http://workshare.com/compareservices/5.0/comparewebservice/Ping", ReplyAction = "http://workshare.com/compareservices/5.0/comparewebservice/PingResponse")]
        Workshare.Document.Services.Compare.Sample.CompareProxy.CompareResults Ping();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComparerChannel : Workshare.Document.Services.Compare.Sample.CompareProxy.IComparer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComparerClient : System.ServiceModel.ClientBase<Workshare.Document.Services.Compare.Sample.CompareProxy.IComparer>, Workshare.Document.Services.Compare.Sample.CompareProxy.IComparer {
        
        public ComparerClient() {
        }
        
        public ComparerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComparerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComparerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComparerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Authenticate(string sRealm, string sUser, string sPassword) {
            return base.Channel.Authenticate(sRealm, sUser, sPassword);
        }
        
        public string GetVersion() {
            return base.Channel.GetVersion();
        }
        
        public string GetCompositorVersion() {
            return base.Channel.GetCompositorVersion();
        }
        
        public string GetOptionsSet() {
            return base.Channel.GetOptionsSet();
        }
        
        public bool SetOptionsSet(string sOptionsSet) {
            return base.Channel.SetOptionsSet(sOptionsSet);
        }
        
        public Workshare.Document.Services.Compare.Sample.CompareProxy.CompareResults Execute(byte[] OriginalData, byte[] ModifiedData, Workshare.Document.Services.Compare.Sample.CompareProxy.ResponseOptions ResponseOption, string CompareOptions) {
            return base.Channel.Execute(OriginalData, ModifiedData, ResponseOption, CompareOptions);
        }
        
        public Workshare.Document.Services.Compare.Sample.CompareProxy.CompareResults ExecuteEx(Workshare.Document.Services.Compare.Sample.CompareProxy.ExecuteParams execParams) {
            return base.Channel.ExecuteEx(execParams);
        }
        
        public Workshare.Document.Services.Compare.Sample.CompareProxy.CompareResults Ping() {
            return base.Channel.Ping();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://workshare.com/compareservices/1.1/comparewebservice/", ConfigurationName="CompareProxy.ILegacyComparer")]
    public interface ILegacyComparer {
        
        // CODEGEN: Generating message contract since element name sDomain from namespace http://workshare.com/compareservices/1.1/comparewebservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/1.1/comparewebservice/Authenticate", ReplyAction="http://workshare.com/compareservices/1.1/comparewebservice/AuthenticateResponse")]
        Workshare.Document.Services.Compare.Sample.CompareProxy.AuthenticateResponse Authenticate(Workshare.Document.Services.Compare.Sample.CompareProxy.AuthenticateRequest request);
        
        // CODEGEN: Generating message contract since element name compareOptions from namespace http://workshare.com/compareservices/1.1/comparewebservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/1.1/comparewebservice/Execute", ReplyAction="http://workshare.com/compareservices/1.1/comparewebservice/ExecuteResponse")]
        Workshare.Document.Services.Compare.Sample.CompareProxy.ExecuteResponse Execute(Workshare.Document.Services.Compare.Sample.CompareProxy.ExecuteRequest request);
        
        // CODEGEN: Generating message contract since element name original from namespace http://workshare.com/compareservices/1.1/comparewebservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/1.1/comparewebservice/Execute2", ReplyAction="http://workshare.com/compareservices/1.1/comparewebservice/Execute2Response")]
        Workshare.Document.Services.Compare.Sample.CompareProxy.Execute2Response Execute2(Workshare.Document.Services.Compare.Sample.CompareProxy.Execute2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authenticate", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/", Order=0)]
        public Workshare.Document.Services.Compare.Sample.CompareProxy.AuthenticateRequestBody Body;
        
        public AuthenticateRequest() {
        }
        
        public AuthenticateRequest(Workshare.Document.Services.Compare.Sample.CompareProxy.AuthenticateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://workshare.com/compareservices/1.1/comparewebservice/")]
    public partial class AuthenticateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sDomain;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sPass;
        
        public AuthenticateRequestBody() {
        }
        
        public AuthenticateRequestBody(string sDomain, string sUser, string sPass) {
            this.sDomain = sDomain;
            this.sUser = sUser;
            this.sPass = sPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateResponse", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/", Order=0)]
        public Workshare.Document.Services.Compare.Sample.CompareProxy.AuthenticateResponseBody Body;
        
        public AuthenticateResponse() {
        }
        
        public AuthenticateResponse(Workshare.Document.Services.Compare.Sample.CompareProxy.AuthenticateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://workshare.com/compareservices/1.1/comparewebservice/")]
    public partial class AuthenticateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AuthenticateResult;
        
        public AuthenticateResponseBody() {
        }
        
        public AuthenticateResponseBody(bool AuthenticateResult) {
            this.AuthenticateResult = AuthenticateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/", Order=0)]
        public Workshare.Document.Services.Compare.Sample.CompareProxy.ExecuteRequestBody Body;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(Workshare.Document.Services.Compare.Sample.CompareProxy.ExecuteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://workshare.com/compareservices/1.1/comparewebservice/")]
    public partial class ExecuteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public Workshare.Document.Services.Compare.Sample.CompareProxy.CompareResponseFlags flags;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string compareOptions;
        
        public ExecuteRequestBody() {
        }
        
        public ExecuteRequestBody(Workshare.Document.Services.Compare.Sample.CompareProxy.CompareResponseFlags flags, string compareOptions) {
            this.flags = flags;
            this.compareOptions = compareOptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteResponse", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/", Order=0)]
        public Workshare.Document.Services.Compare.Sample.CompareProxy.ExecuteResponseBody Body;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(Workshare.Document.Services.Compare.Sample.CompareProxy.ExecuteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ExecuteResponseBody {
        
        public ExecuteResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute2", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/", Order=0)]
        public Workshare.Document.Services.Compare.Sample.CompareProxy.Execute2RequestBody Body;
        
        public Execute2Request() {
        }
        
        public Execute2Request(Workshare.Document.Services.Compare.Sample.CompareProxy.Execute2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://workshare.com/compareservices/1.1/comparewebservice/")]
    public partial class Execute2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] original;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] modified;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Workshare.Document.Services.Compare.Sample.CompareProxy.CompareResponseFlags flags;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string compareOptions;
        
        public Execute2RequestBody() {
        }
        
        public Execute2RequestBody(byte[] original, byte[] modified, Workshare.Document.Services.Compare.Sample.CompareProxy.CompareResponseFlags flags, string compareOptions) {
            this.original = original;
            this.modified = modified;
            this.flags = flags;
            this.compareOptions = compareOptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute2Response", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/", Order=0)]
        public Workshare.Document.Services.Compare.Sample.CompareProxy.Execute2ResponseBody Body;
        
        public Execute2Response() {
        }
        
        public Execute2Response(Workshare.Document.Services.Compare.Sample.CompareProxy.Execute2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://workshare.com/compareservices/1.1/comparewebservice/")]
    public partial class Execute2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Workshare.Document.Services.Compare.Sample.CompareProxy.CompareResult Execute2Result;
        
        public Execute2ResponseBody() {
        }
        
        public Execute2ResponseBody(Workshare.Document.Services.Compare.Sample.CompareProxy.CompareResult Execute2Result) {
            this.Execute2Result = Execute2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILegacyComparerChannel : Workshare.Document.Services.Compare.Sample.CompareProxy.ILegacyComparer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LegacyComparerClient : System.ServiceModel.ClientBase<Workshare.Document.Services.Compare.Sample.CompareProxy.ILegacyComparer>, Workshare.Document.Services.Compare.Sample.CompareProxy.ILegacyComparer {
        
        public LegacyComparerClient() {
        }
        
        public LegacyComparerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LegacyComparerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LegacyComparerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LegacyComparerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Workshare.Document.Services.Compare.Sample.CompareProxy.AuthenticateResponse Workshare.Document.Services.Compare.Sample.CompareProxy.ILegacyComparer.Authenticate(Workshare.Document.Services.Compare.Sample.CompareProxy.AuthenticateRequest request) {
            return base.Channel.Authenticate(request);
        }
        
        public bool Authenticate(string sDomain, string sUser, string sPass) {
            Workshare.Document.Services.Compare.Sample.CompareProxy.AuthenticateRequest inValue = new Workshare.Document.Services.Compare.Sample.CompareProxy.AuthenticateRequest();
            inValue.Body = new Workshare.Document.Services.Compare.Sample.CompareProxy.AuthenticateRequestBody();
            inValue.Body.sDomain = sDomain;
            inValue.Body.sUser = sUser;
            inValue.Body.sPass = sPass;
            Workshare.Document.Services.Compare.Sample.CompareProxy.AuthenticateResponse retVal = ((Workshare.Document.Services.Compare.Sample.CompareProxy.ILegacyComparer)(this)).Authenticate(inValue);
            return retVal.Body.AuthenticateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Workshare.Document.Services.Compare.Sample.CompareProxy.ExecuteResponse Workshare.Document.Services.Compare.Sample.CompareProxy.ILegacyComparer.Execute(Workshare.Document.Services.Compare.Sample.CompareProxy.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public void Execute(Workshare.Document.Services.Compare.Sample.CompareProxy.CompareResponseFlags flags, string compareOptions) {
            Workshare.Document.Services.Compare.Sample.CompareProxy.ExecuteRequest inValue = new Workshare.Document.Services.Compare.Sample.CompareProxy.ExecuteRequest();
            inValue.Body = new Workshare.Document.Services.Compare.Sample.CompareProxy.ExecuteRequestBody();
            inValue.Body.flags = flags;
            inValue.Body.compareOptions = compareOptions;
            Workshare.Document.Services.Compare.Sample.CompareProxy.ExecuteResponse retVal = ((Workshare.Document.Services.Compare.Sample.CompareProxy.ILegacyComparer)(this)).Execute(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Workshare.Document.Services.Compare.Sample.CompareProxy.Execute2Response Workshare.Document.Services.Compare.Sample.CompareProxy.ILegacyComparer.Execute2(Workshare.Document.Services.Compare.Sample.CompareProxy.Execute2Request request) {
            return base.Channel.Execute2(request);
        }
        
        public Workshare.Document.Services.Compare.Sample.CompareProxy.CompareResult Execute2(byte[] original, byte[] modified, Workshare.Document.Services.Compare.Sample.CompareProxy.CompareResponseFlags flags, string compareOptions) {
            Workshare.Document.Services.Compare.Sample.CompareProxy.Execute2Request inValue = new Workshare.Document.Services.Compare.Sample.CompareProxy.Execute2Request();
            inValue.Body = new Workshare.Document.Services.Compare.Sample.CompareProxy.Execute2RequestBody();
            inValue.Body.original = original;
            inValue.Body.modified = modified;
            inValue.Body.flags = flags;
            inValue.Body.compareOptions = compareOptions;
            Workshare.Document.Services.Compare.Sample.CompareProxy.Execute2Response retVal = ((Workshare.Document.Services.Compare.Sample.CompareProxy.ILegacyComparer)(this)).Execute2(inValue);
            return retVal.Body.Execute2Result;
        }
    }
}
