//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompareServer.Domain.ComparerProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOptions", Namespace="http://workshare.com/compareservices/5.0/comparewebservice/")]
    public enum ResponseOptions : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rtf = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Xml = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RtfWithSummary = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wdf = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WdfWithSummary = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Doc = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DocWithSummary = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DocX = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DocXWithSummary = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pdf = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PdfWithSummary = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RedlinMl = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RedlinMlAndRtf = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RedlinMlAndSummary = 66,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RedlinMlAndRtfAndSummary = 67,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RedlinMlAndDoc = 72,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RedlinMlAndDocAndSummary = 74,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RedlinMlAndDocX = 80,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RedlinMlAndDocXAndSummary = 82,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RedlinMlAndPdf = 96,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RedlinMlAndPdfAndSummary = 98,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompareResults", Namespace="http://workshare.com/compareservices/5.0/comparewebservice/")]
    [System.SerializableAttribute()]
    public partial class CompareResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RedlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RedlineMlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SummaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Redline {
            get {
                return this.RedlineField;
            }
            set {
                if ((object.ReferenceEquals(this.RedlineField, value) != true)) {
                    this.RedlineField = value;
                    this.RaisePropertyChanged("Redline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RedlineMl {
            get {
                return this.RedlineMlField;
            }
            set {
                if ((object.ReferenceEquals(this.RedlineMlField, value) != true)) {
                    this.RedlineMlField = value;
                    this.RaisePropertyChanged("RedlineMl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary {
            get {
                return this.SummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryField, value) != true)) {
                    this.SummaryField = value;
                    this.RaisePropertyChanged("Summary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecuteParams", Namespace="http://workshare.com/compareservices/5.0/comparewebservice/")]
    [System.SerializableAttribute()]
    public partial class ExecuteParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompareOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CompareServer.Domain.ComparerProxy.DocumentInfo ModifiedDocumentInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] OriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CompareServer.Domain.ComparerProxy.DocumentInfo OriginalDocumentInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CompareServer.Domain.ComparerProxy.ResponseOptions ResponseOptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompareOptions {
            get {
                return this.CompareOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.CompareOptionsField, value) != true)) {
                    this.CompareOptionsField = value;
                    this.RaisePropertyChanged("CompareOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Modified {
            get {
                return this.ModifiedField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedField, value) != true)) {
                    this.ModifiedField = value;
                    this.RaisePropertyChanged("Modified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CompareServer.Domain.ComparerProxy.DocumentInfo ModifiedDocumentInfo {
            get {
                return this.ModifiedDocumentInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedDocumentInfoField, value) != true)) {
                    this.ModifiedDocumentInfoField = value;
                    this.RaisePropertyChanged("ModifiedDocumentInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Original {
            get {
                return this.OriginalField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalField, value) != true)) {
                    this.OriginalField = value;
                    this.RaisePropertyChanged("Original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CompareServer.Domain.ComparerProxy.DocumentInfo OriginalDocumentInfo {
            get {
                return this.OriginalDocumentInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalDocumentInfoField, value) != true)) {
                    this.OriginalDocumentInfoField = value;
                    this.RaisePropertyChanged("OriginalDocumentInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CompareServer.Domain.ComparerProxy.ResponseOptions ResponseOption {
            get {
                return this.ResponseOptionField;
            }
            set {
                if ((this.ResponseOptionField.Equals(value) != true)) {
                    this.ResponseOptionField = value;
                    this.RaisePropertyChanged("ResponseOption");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentInfo", Namespace="http://workshare.com/compareservices/5.0/comparewebservice/")]
    [System.SerializableAttribute()]
    public partial class DocumentInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentSourceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentDescription {
            get {
                return this.DocumentDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentDescriptionField, value) != true)) {
                    this.DocumentDescriptionField = value;
                    this.RaisePropertyChanged("DocumentDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentSource {
            get {
                return this.DocumentSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentSourceField, value) != true)) {
                    this.DocumentSourceField = value;
                    this.RaisePropertyChanged("DocumentSource");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompareResponseFlags", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/")]
    public enum CompareResponseFlags : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rtf = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Xml = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Both = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DocX = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pdf = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DocXWithXml = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PdfWithXml = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompareResult", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/")]
    [System.SerializableAttribute()]
    public partial class CompareResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RedlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.Linq.XElement SummaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] Redline {
            get {
                return this.RedlineField;
            }
            set {
                if ((object.ReferenceEquals(this.RedlineField, value) != true)) {
                    this.RedlineField = value;
                    this.RaisePropertyChanged("Redline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Xml.Linq.XElement Summary {
            get {
                return this.SummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryField, value) != true)) {
                    this.SummaryField = value;
                    this.RaisePropertyChanged("Summary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChunkedExecuteParams", Namespace="http://workshare.com/compareservices/5.0/comparewebservice/")]
    [System.SerializableAttribute()]
    public partial class ChunkedExecuteParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompareOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CompareServer.Domain.ComparerProxy.DocumentInfo ModifiedDocumentInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CompareServer.Domain.ComparerProxy.DocumentInfo OriginalDocumentInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CompareServer.Domain.ComparerProxy.ResponseOptions ResponseOptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompareOptions {
            get {
                return this.CompareOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.CompareOptionsField, value) != true)) {
                    this.CompareOptionsField = value;
                    this.RaisePropertyChanged("CompareOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Modified {
            get {
                return this.ModifiedField;
            }
            set {
                if ((this.ModifiedField.Equals(value) != true)) {
                    this.ModifiedField = value;
                    this.RaisePropertyChanged("Modified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CompareServer.Domain.ComparerProxy.DocumentInfo ModifiedDocumentInfo {
            get {
                return this.ModifiedDocumentInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedDocumentInfoField, value) != true)) {
                    this.ModifiedDocumentInfoField = value;
                    this.RaisePropertyChanged("ModifiedDocumentInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Original {
            get {
                return this.OriginalField;
            }
            set {
                if ((this.OriginalField.Equals(value) != true)) {
                    this.OriginalField = value;
                    this.RaisePropertyChanged("Original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CompareServer.Domain.ComparerProxy.DocumentInfo OriginalDocumentInfo {
            get {
                return this.OriginalDocumentInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalDocumentInfoField, value) != true)) {
                    this.OriginalDocumentInfoField = value;
                    this.RaisePropertyChanged("OriginalDocumentInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CompareServer.Domain.ComparerProxy.ResponseOptions ResponseOption {
            get {
                return this.ResponseOptionField;
            }
            set {
                if ((this.ResponseOptionField.Equals(value) != true)) {
                    this.ResponseOptionField = value;
                    this.RaisePropertyChanged("ResponseOption");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerformanceResults", Namespace="http://workshare.com/compareservices/5.2/comparewebservice/")]
    [System.SerializableAttribute()]
    public partial class PerformanceResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan ComparisonTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan ModifiedConversionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan ModifiedPreProcessingTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan OriginalConversionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan OriginalPreProcessingTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan ResultsProcessingTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan TotalExecutionTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan ComparisonTime {
            get {
                return this.ComparisonTimeField;
            }
            set {
                if ((this.ComparisonTimeField.Equals(value) != true)) {
                    this.ComparisonTimeField = value;
                    this.RaisePropertyChanged("ComparisonTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan ModifiedConversionTime {
            get {
                return this.ModifiedConversionTimeField;
            }
            set {
                if ((this.ModifiedConversionTimeField.Equals(value) != true)) {
                    this.ModifiedConversionTimeField = value;
                    this.RaisePropertyChanged("ModifiedConversionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan ModifiedPreProcessingTime {
            get {
                return this.ModifiedPreProcessingTimeField;
            }
            set {
                if ((this.ModifiedPreProcessingTimeField.Equals(value) != true)) {
                    this.ModifiedPreProcessingTimeField = value;
                    this.RaisePropertyChanged("ModifiedPreProcessingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan OriginalConversionTime {
            get {
                return this.OriginalConversionTimeField;
            }
            set {
                if ((this.OriginalConversionTimeField.Equals(value) != true)) {
                    this.OriginalConversionTimeField = value;
                    this.RaisePropertyChanged("OriginalConversionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan OriginalPreProcessingTime {
            get {
                return this.OriginalPreProcessingTimeField;
            }
            set {
                if ((this.OriginalPreProcessingTimeField.Equals(value) != true)) {
                    this.OriginalPreProcessingTimeField = value;
                    this.RaisePropertyChanged("OriginalPreProcessingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan ResultsProcessingTime {
            get {
                return this.ResultsProcessingTimeField;
            }
            set {
                if ((this.ResultsProcessingTimeField.Equals(value) != true)) {
                    this.ResultsProcessingTimeField = value;
                    this.RaisePropertyChanged("ResultsProcessingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan TotalExecutionTime {
            get {
                return this.TotalExecutionTimeField;
            }
            set {
                if ((this.TotalExecutionTimeField.Equals(value) != true)) {
                    this.TotalExecutionTimeField = value;
                    this.RaisePropertyChanged("TotalExecutionTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", ConfigurationName="ComparerProxy.IComparer")]
    public interface IComparer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/5.0/comparewebservice/Authenticate", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/AuthenticateResponse")]
        bool Authenticate(string sRealm, string sUser, string sPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/5.0/comparewebservice/GetVersion", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/GetVersionResponse")]
        string GetVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/5.0/comparewebservice/GetCompositorVersion", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/GetCompositorVersionRe" +
            "sponse")]
        string GetCompositorVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/5.0/comparewebservice/GetOptionsSet", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/GetOptionsSetResponse")]
        string GetOptionsSet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/5.0/comparewebservice/SetOptionsSet", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/SetOptionsSetResponse")]
        bool SetOptionsSet(string sOptionsSet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/5.0/comparewebservice/Execute", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/ExecuteResponse")]
        CompareServer.Domain.ComparerProxy.CompareResults Execute(byte[] OriginalData, byte[] ModifiedData, CompareServer.Domain.ComparerProxy.ResponseOptions ResponseOption, string CompareOptions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/5.0/comparewebservice/ExecuteEx", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/ExecuteExResponse")]
        CompareServer.Domain.ComparerProxy.CompareResults ExecuteEx(CompareServer.Domain.ComparerProxy.ExecuteParams execParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/5.0/comparewebservice/Ping", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/PingResponse")]
        CompareServer.Domain.ComparerProxy.CompareResults Ping();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComparerChannel : CompareServer.Domain.ComparerProxy.IComparer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComparerClient : System.ServiceModel.ClientBase<CompareServer.Domain.ComparerProxy.IComparer>, CompareServer.Domain.ComparerProxy.IComparer {
        
        public ComparerClient() {
        }
        
        public ComparerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComparerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComparerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComparerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Authenticate(string sRealm, string sUser, string sPassword) {
            return base.Channel.Authenticate(sRealm, sUser, sPassword);
        }
        
        public string GetVersion() {
            return base.Channel.GetVersion();
        }
        
        public string GetCompositorVersion() {
            return base.Channel.GetCompositorVersion();
        }
        
        public string GetOptionsSet() {
            return base.Channel.GetOptionsSet();
        }
        
        public bool SetOptionsSet(string sOptionsSet) {
            return base.Channel.SetOptionsSet(sOptionsSet);
        }
        
        public CompareServer.Domain.ComparerProxy.CompareResults Execute(byte[] OriginalData, byte[] ModifiedData, CompareServer.Domain.ComparerProxy.ResponseOptions ResponseOption, string CompareOptions) {
            return base.Channel.Execute(OriginalData, ModifiedData, ResponseOption, CompareOptions);
        }
        
        public CompareServer.Domain.ComparerProxy.CompareResults ExecuteEx(CompareServer.Domain.ComparerProxy.ExecuteParams execParams) {
            return base.Channel.ExecuteEx(execParams);
        }
        
        public CompareServer.Domain.ComparerProxy.CompareResults Ping() {
            return base.Channel.Ping();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://workshare.com/compareservices/1.1/comparewebservice/", ConfigurationName="ComparerProxy.ILegacyComparer")]
    public interface ILegacyComparer {
        
        // CODEGEN: Generating message contract since element name sDomain from namespace http://workshare.com/compareservices/1.1/comparewebservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/1.1/comparewebservice/Authenticate", ReplyAction="http://workshare.com/compareservices/1.1/comparewebservice/AuthenticateResponse")]
        CompareServer.Domain.ComparerProxy.AuthenticateResponse Authenticate(CompareServer.Domain.ComparerProxy.AuthenticateRequest request);
        
        // CODEGEN: Generating message contract since element name compareOptions from namespace http://workshare.com/compareservices/1.1/comparewebservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/1.1/comparewebservice/Execute", ReplyAction="http://workshare.com/compareservices/1.1/comparewebservice/ExecuteResponse")]
        CompareServer.Domain.ComparerProxy.ExecuteResponse Execute(CompareServer.Domain.ComparerProxy.ExecuteRequest request);
        
        // CODEGEN: Generating message contract since element name original from namespace http://workshare.com/compareservices/1.1/comparewebservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/1.1/comparewebservice/Execute2", ReplyAction="http://workshare.com/compareservices/1.1/comparewebservice/Execute2Response")]
        CompareServer.Domain.ComparerProxy.Execute2Response Execute2(CompareServer.Domain.ComparerProxy.Execute2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authenticate", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/", Order=0)]
        public CompareServer.Domain.ComparerProxy.AuthenticateRequestBody Body;
        
        public AuthenticateRequest() {
        }
        
        public AuthenticateRequest(CompareServer.Domain.ComparerProxy.AuthenticateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://workshare.com/compareservices/1.1/comparewebservice/")]
    public partial class AuthenticateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sDomain;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sPass;
        
        public AuthenticateRequestBody() {
        }
        
        public AuthenticateRequestBody(string sDomain, string sUser, string sPass) {
            this.sDomain = sDomain;
            this.sUser = sUser;
            this.sPass = sPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateResponse", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/", Order=0)]
        public CompareServer.Domain.ComparerProxy.AuthenticateResponseBody Body;
        
        public AuthenticateResponse() {
        }
        
        public AuthenticateResponse(CompareServer.Domain.ComparerProxy.AuthenticateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://workshare.com/compareservices/1.1/comparewebservice/")]
    public partial class AuthenticateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AuthenticateResult;
        
        public AuthenticateResponseBody() {
        }
        
        public AuthenticateResponseBody(bool AuthenticateResult) {
            this.AuthenticateResult = AuthenticateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/", Order=0)]
        public CompareServer.Domain.ComparerProxy.ExecuteRequestBody Body;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(CompareServer.Domain.ComparerProxy.ExecuteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://workshare.com/compareservices/1.1/comparewebservice/")]
    public partial class ExecuteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public CompareServer.Domain.ComparerProxy.CompareResponseFlags flags;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string compareOptions;
        
        public ExecuteRequestBody() {
        }
        
        public ExecuteRequestBody(CompareServer.Domain.ComparerProxy.CompareResponseFlags flags, string compareOptions) {
            this.flags = flags;
            this.compareOptions = compareOptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteResponse", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/", Order=0)]
        public CompareServer.Domain.ComparerProxy.ExecuteResponseBody Body;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(CompareServer.Domain.ComparerProxy.ExecuteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ExecuteResponseBody {
        
        public ExecuteResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute2", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/", Order=0)]
        public CompareServer.Domain.ComparerProxy.Execute2RequestBody Body;
        
        public Execute2Request() {
        }
        
        public Execute2Request(CompareServer.Domain.ComparerProxy.Execute2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://workshare.com/compareservices/1.1/comparewebservice/")]
    public partial class Execute2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] original;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] modified;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public CompareServer.Domain.ComparerProxy.CompareResponseFlags flags;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string compareOptions;
        
        public Execute2RequestBody() {
        }
        
        public Execute2RequestBody(byte[] original, byte[] modified, CompareServer.Domain.ComparerProxy.CompareResponseFlags flags, string compareOptions) {
            this.original = original;
            this.modified = modified;
            this.flags = flags;
            this.compareOptions = compareOptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute2Response", Namespace="http://workshare.com/compareservices/1.1/comparewebservice/", Order=0)]
        public CompareServer.Domain.ComparerProxy.Execute2ResponseBody Body;
        
        public Execute2Response() {
        }
        
        public Execute2Response(CompareServer.Domain.ComparerProxy.Execute2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://workshare.com/compareservices/1.1/comparewebservice/")]
    public partial class Execute2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CompareServer.Domain.ComparerProxy.CompareResult Execute2Result;
        
        public Execute2ResponseBody() {
        }
        
        public Execute2ResponseBody(CompareServer.Domain.ComparerProxy.CompareResult Execute2Result) {
            this.Execute2Result = Execute2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILegacyComparerChannel : CompareServer.Domain.ComparerProxy.ILegacyComparer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LegacyComparerClient : System.ServiceModel.ClientBase<CompareServer.Domain.ComparerProxy.ILegacyComparer>, CompareServer.Domain.ComparerProxy.ILegacyComparer {
        
        public LegacyComparerClient() {
        }
        
        public LegacyComparerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LegacyComparerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LegacyComparerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LegacyComparerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompareServer.Domain.ComparerProxy.AuthenticateResponse CompareServer.Domain.ComparerProxy.ILegacyComparer.Authenticate(CompareServer.Domain.ComparerProxy.AuthenticateRequest request) {
            return base.Channel.Authenticate(request);
        }
        
        public bool Authenticate(string sDomain, string sUser, string sPass) {
            CompareServer.Domain.ComparerProxy.AuthenticateRequest inValue = new CompareServer.Domain.ComparerProxy.AuthenticateRequest();
            inValue.Body = new CompareServer.Domain.ComparerProxy.AuthenticateRequestBody();
            inValue.Body.sDomain = sDomain;
            inValue.Body.sUser = sUser;
            inValue.Body.sPass = sPass;
            CompareServer.Domain.ComparerProxy.AuthenticateResponse retVal = ((CompareServer.Domain.ComparerProxy.ILegacyComparer)(this)).Authenticate(inValue);
            return retVal.Body.AuthenticateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompareServer.Domain.ComparerProxy.ExecuteResponse CompareServer.Domain.ComparerProxy.ILegacyComparer.Execute(CompareServer.Domain.ComparerProxy.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public void Execute(CompareServer.Domain.ComparerProxy.CompareResponseFlags flags, string compareOptions) {
            CompareServer.Domain.ComparerProxy.ExecuteRequest inValue = new CompareServer.Domain.ComparerProxy.ExecuteRequest();
            inValue.Body = new CompareServer.Domain.ComparerProxy.ExecuteRequestBody();
            inValue.Body.flags = flags;
            inValue.Body.compareOptions = compareOptions;
            CompareServer.Domain.ComparerProxy.ExecuteResponse retVal = ((CompareServer.Domain.ComparerProxy.ILegacyComparer)(this)).Execute(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompareServer.Domain.ComparerProxy.Execute2Response CompareServer.Domain.ComparerProxy.ILegacyComparer.Execute2(CompareServer.Domain.ComparerProxy.Execute2Request request) {
            return base.Channel.Execute2(request);
        }
        
        public CompareServer.Domain.ComparerProxy.CompareResult Execute2(byte[] original, byte[] modified, CompareServer.Domain.ComparerProxy.CompareResponseFlags flags, string compareOptions) {
            CompareServer.Domain.ComparerProxy.Execute2Request inValue = new CompareServer.Domain.ComparerProxy.Execute2Request();
            inValue.Body = new CompareServer.Domain.ComparerProxy.Execute2RequestBody();
            inValue.Body.original = original;
            inValue.Body.modified = modified;
            inValue.Body.flags = flags;
            inValue.Body.compareOptions = compareOptions;
            CompareServer.Domain.ComparerProxy.Execute2Response retVal = ((CompareServer.Domain.ComparerProxy.ILegacyComparer)(this)).Execute2(inValue);
            return retVal.Body.Execute2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://workshare.com/compareservices/5.2/comparewebservice/", ConfigurationName="ComparerProxy.IComparerChunked")]
    public interface IComparerChunked {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://workshare.com/compareservices/5.0/comparewebservice/) of message AuthenticateRequest does not match the default value (http://workshare.com/compareservices/5.2/comparewebservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/5.0/comparewebservice/Authenticate", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/AuthenticateResponse")]
        CompareServer.Domain.ComparerProxy.AuthenticateResponse1 Authenticate(CompareServer.Domain.ComparerProxy.AuthenticateRequest1 request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://workshare.com/compareservices/5.0/comparewebservice/) of message GetVersionRequest does not match the default value (http://workshare.com/compareservices/5.2/comparewebservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/5.0/comparewebservice/GetVersion", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/GetVersionResponse")]
        CompareServer.Domain.ComparerProxy.GetVersionResponse GetVersion(CompareServer.Domain.ComparerProxy.GetVersionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://workshare.com/compareservices/5.0/comparewebservice/) of message GetCompositorVersionRequest does not match the default value (http://workshare.com/compareservices/5.2/comparewebservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/5.0/comparewebservice/GetCompositorVersion", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/GetCompositorVersionRe" +
            "sponse")]
        CompareServer.Domain.ComparerProxy.GetCompositorVersionResponse GetCompositorVersion(CompareServer.Domain.ComparerProxy.GetCompositorVersionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://workshare.com/compareservices/5.0/comparewebservice/) of message GetOptionsSetRequest does not match the default value (http://workshare.com/compareservices/5.2/comparewebservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/5.0/comparewebservice/GetOptionsSet", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/GetOptionsSetResponse")]
        CompareServer.Domain.ComparerProxy.GetOptionsSetResponse GetOptionsSet(CompareServer.Domain.ComparerProxy.GetOptionsSetRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://workshare.com/compareservices/5.0/comparewebservice/) of message SetOptionsSetRequest does not match the default value (http://workshare.com/compareservices/5.2/comparewebservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/5.0/comparewebservice/SetOptionsSet", ReplyAction="http://workshare.com/compareservices/5.0/comparewebservice/SetOptionsSetResponse")]
        CompareServer.Domain.ComparerProxy.SetOptionsSetResponse SetOptionsSet(CompareServer.Domain.ComparerProxy.SetOptionsSetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/5.2/comparewebservice/InitialiseFile", ReplyAction="http://workshare.com/compareservices/5.2/comparewebservice/InitialiseFileResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://workshare.com/compareservices/5.2/comparewebservice/IComparerChunked/Initi" +
            "aliseFileStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Guid InitialiseFile(string fileID, long sizeBytes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/5.2/comparewebservice/ReleaseFile", ReplyAction="http://workshare.com/compareservices/5.2/comparewebservice/ReleaseFileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://workshare.com/compareservices/5.2/comparewebservice/IComparerChunked/Relea" +
            "seFileStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        void ReleaseFile(System.Guid fileGuid);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://workshare.com/compareservices/5.2/comparewebservice/ReleaseAll")]
        void ReleaseAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/5.2/comparewebservice/AppendOriginalFile", ReplyAction="http://workshare.com/compareservices/5.2/comparewebservice/AppendOriginalFileResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://workshare.com/compareservices/5.2/comparewebservice/IComparerChunked/Appen" +
            "dFileStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        void AppendFile(System.Guid guidFile, byte[] fileChunk, long previousBytesSent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/5.2/comparewebservice/Compare", ReplyAction="http://workshare.com/compareservices/5.2/comparewebservice/CompareResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://workshare.com/compareservices/5.2/comparewebservice/IComparerChunked/Compa" +
            "reStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        CompareServer.Domain.ComparerProxy.CompareResults Compare(System.Guid guidOriginalFile, System.Guid guidModifiedFile, CompareServer.Domain.ComparerProxy.ResponseOptions ResponseOption, string CompareOptions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/5.2/comparewebservice/CompareEx", ReplyAction="http://workshare.com/compareservices/5.2/comparewebservice/CompareExResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://workshare.com/compareservices/5.2/comparewebservice/IComparerChunked/Compa" +
            "reExStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        CompareServer.Domain.ComparerProxy.CompareResults CompareEx(CompareServer.Domain.ComparerProxy.ChunkedExecuteParams executeParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://workshare.com/compareservices/5.2/comparewebservice/Benchmark", ReplyAction="http://workshare.com/compareservices/5.2/comparewebservice/BenchmarkResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://workshare.com/compareservices/5.2/comparewebservice/IComparerChunked/Bench" +
            "markStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        CompareServer.Domain.ComparerProxy.PerformanceResults Benchmark(System.Guid guidOriginalFile, System.Guid guidModifiedFile, CompareServer.Domain.ComparerProxy.ResponseOptions ResponseOption, string CompareOptions);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Authenticate", WrapperNamespace="http://workshare.com/compareservices/5.0/comparewebservice/", IsWrapped=true)]
    public partial class AuthenticateRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", Order=0)]
        public string sRealm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", Order=1)]
        public string sUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", Order=2)]
        public string sPassword;
        
        public AuthenticateRequest1() {
        }
        
        public AuthenticateRequest1(string sRealm, string sUser, string sPassword) {
            this.sRealm = sRealm;
            this.sUser = sUser;
            this.sPassword = sPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateResponse", WrapperNamespace="http://workshare.com/compareservices/5.0/comparewebservice/", IsWrapped=true)]
    public partial class AuthenticateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", Order=0)]
        public bool AuthenticateResult;
        
        public AuthenticateResponse1() {
        }
        
        public AuthenticateResponse1(bool AuthenticateResult) {
            this.AuthenticateResult = AuthenticateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVersion", WrapperNamespace="http://workshare.com/compareservices/5.0/comparewebservice/", IsWrapped=true)]
    public partial class GetVersionRequest {
        
        public GetVersionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVersionResponse", WrapperNamespace="http://workshare.com/compareservices/5.0/comparewebservice/", IsWrapped=true)]
    public partial class GetVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", Order=0)]
        public string GetVersionResult;
        
        public GetVersionResponse() {
        }
        
        public GetVersionResponse(string GetVersionResult) {
            this.GetVersionResult = GetVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompositorVersion", WrapperNamespace="http://workshare.com/compareservices/5.0/comparewebservice/", IsWrapped=true)]
    public partial class GetCompositorVersionRequest {
        
        public GetCompositorVersionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompositorVersionResponse", WrapperNamespace="http://workshare.com/compareservices/5.0/comparewebservice/", IsWrapped=true)]
    public partial class GetCompositorVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", Order=0)]
        public string GetCompositorVersionResult;
        
        public GetCompositorVersionResponse() {
        }
        
        public GetCompositorVersionResponse(string GetCompositorVersionResult) {
            this.GetCompositorVersionResult = GetCompositorVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOptionsSet", WrapperNamespace="http://workshare.com/compareservices/5.0/comparewebservice/", IsWrapped=true)]
    public partial class GetOptionsSetRequest {
        
        public GetOptionsSetRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOptionsSetResponse", WrapperNamespace="http://workshare.com/compareservices/5.0/comparewebservice/", IsWrapped=true)]
    public partial class GetOptionsSetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", Order=0)]
        public string GetOptionsSetResult;
        
        public GetOptionsSetResponse() {
        }
        
        public GetOptionsSetResponse(string GetOptionsSetResult) {
            this.GetOptionsSetResult = GetOptionsSetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetOptionsSet", WrapperNamespace="http://workshare.com/compareservices/5.0/comparewebservice/", IsWrapped=true)]
    public partial class SetOptionsSetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", Order=0)]
        public string sOptionsSet;
        
        public SetOptionsSetRequest() {
        }
        
        public SetOptionsSetRequest(string sOptionsSet) {
            this.sOptionsSet = sOptionsSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetOptionsSetResponse", WrapperNamespace="http://workshare.com/compareservices/5.0/comparewebservice/", IsWrapped=true)]
    public partial class SetOptionsSetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://workshare.com/compareservices/5.0/comparewebservice/", Order=0)]
        public bool SetOptionsSetResult;
        
        public SetOptionsSetResponse() {
        }
        
        public SetOptionsSetResponse(bool SetOptionsSetResult) {
            this.SetOptionsSetResult = SetOptionsSetResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComparerChunkedChannel : CompareServer.Domain.ComparerProxy.IComparerChunked, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComparerChunkedClient : System.ServiceModel.ClientBase<CompareServer.Domain.ComparerProxy.IComparerChunked>, CompareServer.Domain.ComparerProxy.IComparerChunked {
        
        public ComparerChunkedClient() {
        }
        
        public ComparerChunkedClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComparerChunkedClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComparerChunkedClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComparerChunkedClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompareServer.Domain.ComparerProxy.AuthenticateResponse1 CompareServer.Domain.ComparerProxy.IComparerChunked.Authenticate(CompareServer.Domain.ComparerProxy.AuthenticateRequest1 request) {
            return base.Channel.Authenticate(request);
        }
        
        public bool Authenticate(string sRealm, string sUser, string sPassword) {
            CompareServer.Domain.ComparerProxy.AuthenticateRequest1 inValue = new CompareServer.Domain.ComparerProxy.AuthenticateRequest1();
            inValue.sRealm = sRealm;
            inValue.sUser = sUser;
            inValue.sPassword = sPassword;
            CompareServer.Domain.ComparerProxy.AuthenticateResponse1 retVal = ((CompareServer.Domain.ComparerProxy.IComparerChunked)(this)).Authenticate(inValue);
            return retVal.AuthenticateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompareServer.Domain.ComparerProxy.GetVersionResponse CompareServer.Domain.ComparerProxy.IComparerChunked.GetVersion(CompareServer.Domain.ComparerProxy.GetVersionRequest request) {
            return base.Channel.GetVersion(request);
        }
        
        public string GetVersion() {
            CompareServer.Domain.ComparerProxy.GetVersionRequest inValue = new CompareServer.Domain.ComparerProxy.GetVersionRequest();
            CompareServer.Domain.ComparerProxy.GetVersionResponse retVal = ((CompareServer.Domain.ComparerProxy.IComparerChunked)(this)).GetVersion(inValue);
            return retVal.GetVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompareServer.Domain.ComparerProxy.GetCompositorVersionResponse CompareServer.Domain.ComparerProxy.IComparerChunked.GetCompositorVersion(CompareServer.Domain.ComparerProxy.GetCompositorVersionRequest request) {
            return base.Channel.GetCompositorVersion(request);
        }
        
        public string GetCompositorVersion() {
            CompareServer.Domain.ComparerProxy.GetCompositorVersionRequest inValue = new CompareServer.Domain.ComparerProxy.GetCompositorVersionRequest();
            CompareServer.Domain.ComparerProxy.GetCompositorVersionResponse retVal = ((CompareServer.Domain.ComparerProxy.IComparerChunked)(this)).GetCompositorVersion(inValue);
            return retVal.GetCompositorVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompareServer.Domain.ComparerProxy.GetOptionsSetResponse CompareServer.Domain.ComparerProxy.IComparerChunked.GetOptionsSet(CompareServer.Domain.ComparerProxy.GetOptionsSetRequest request) {
            return base.Channel.GetOptionsSet(request);
        }
        
        public string GetOptionsSet() {
            CompareServer.Domain.ComparerProxy.GetOptionsSetRequest inValue = new CompareServer.Domain.ComparerProxy.GetOptionsSetRequest();
            CompareServer.Domain.ComparerProxy.GetOptionsSetResponse retVal = ((CompareServer.Domain.ComparerProxy.IComparerChunked)(this)).GetOptionsSet(inValue);
            return retVal.GetOptionsSetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompareServer.Domain.ComparerProxy.SetOptionsSetResponse CompareServer.Domain.ComparerProxy.IComparerChunked.SetOptionsSet(CompareServer.Domain.ComparerProxy.SetOptionsSetRequest request) {
            return base.Channel.SetOptionsSet(request);
        }
        
        public bool SetOptionsSet(string sOptionsSet) {
            CompareServer.Domain.ComparerProxy.SetOptionsSetRequest inValue = new CompareServer.Domain.ComparerProxy.SetOptionsSetRequest();
            inValue.sOptionsSet = sOptionsSet;
            CompareServer.Domain.ComparerProxy.SetOptionsSetResponse retVal = ((CompareServer.Domain.ComparerProxy.IComparerChunked)(this)).SetOptionsSet(inValue);
            return retVal.SetOptionsSetResult;
        }
        
        public System.Guid InitialiseFile(string fileID, long sizeBytes) {
            return base.Channel.InitialiseFile(fileID, sizeBytes);
        }
        
        public void ReleaseFile(System.Guid fileGuid) {
            base.Channel.ReleaseFile(fileGuid);
        }
        
        public void ReleaseAll() {
            base.Channel.ReleaseAll();
        }
        
        public void AppendFile(System.Guid guidFile, byte[] fileChunk, long previousBytesSent) {
            base.Channel.AppendFile(guidFile, fileChunk, previousBytesSent);
        }
        
        public CompareServer.Domain.ComparerProxy.CompareResults Compare(System.Guid guidOriginalFile, System.Guid guidModifiedFile, CompareServer.Domain.ComparerProxy.ResponseOptions ResponseOption, string CompareOptions) {
            return base.Channel.Compare(guidOriginalFile, guidModifiedFile, ResponseOption, CompareOptions);
        }
        
        public CompareServer.Domain.ComparerProxy.CompareResults CompareEx(CompareServer.Domain.ComparerProxy.ChunkedExecuteParams executeParams) {
            return base.Channel.CompareEx(executeParams);
        }
        
        public CompareServer.Domain.ComparerProxy.PerformanceResults Benchmark(System.Guid guidOriginalFile, System.Guid guidModifiedFile, CompareServer.Domain.ComparerProxy.ResponseOptions ResponseOption, string CompareOptions) {
            return base.Channel.Benchmark(guidOriginalFile, guidModifiedFile, ResponseOption, CompareOptions);
        }
    }
}
